-- Generated by database/scripts/build-catalog.mjs — do not edit by hand
-- Primary machine images for catalog machines.

INSERT INTO machine_images (machine_id, image_url, alt_text, sort_order, is_primary)
SELECT m.id, v.image_url, v.alt_text::jsonb, 0, true
FROM machines m
JOIN (VALUES
  ('CY_CHEST_PRESS', '/machinefit/assets/machines/cybex/cy_chest_press.svg', '{"ko":"체스트 프레스","en":"Chest Press"}'),
  ('CY_SHOULDER_PRESS', '/machinefit/assets/machines/cybex/cy_shoulder_press.svg', '{"ko":"숄더 프레스","en":"Shoulder Press"}'),
  ('CY_LAT_PULLDOWN', '/machinefit/assets/machines/cybex/cy_lat_pulldown.svg', '{"ko":"랫 풀다운","en":"Lat Pulldown"}'),
  ('CY_SEATED_ROW', '/machinefit/assets/machines/cybex/cy_seated_row.svg', '{"ko":"시티드 로우","en":"Seated Row"}'),
  ('CY_LEG_PRESS', '/machinefit/assets/machines/cybex/cy_leg_press.svg', '{"ko":"레그 프레스","en":"Leg Press"}'),
  ('CY_LEG_EXTENSION', '/machinefit/assets/machines/cybex/cy_leg_extension.svg', '{"ko":"레그 익스텐션","en":"Leg Extension"}'),
  ('CY_LEG_CURL', '/machinefit/assets/machines/cybex/cy_leg_curl.svg', '{"ko":"레그 컬","en":"Leg Curl"}'),
  ('CY_PEC_FLY', '/machinefit/assets/machines/cybex/cy_pec_fly.svg', '{"ko":"펙 플라이","en":"Pec Fly"}'),
  ('CY_ABDOMINAL', '/machinefit/assets/machines/cybex/cy_abdominal.svg', '{"ko":"어브도미널","en":"Abdominal"}'),
  ('CY_BACK_EXTENSION', '/machinefit/assets/machines/cybex/cy_back_extension.svg', '{"ko":"백 익스텐션","en":"Back Extension"}'),
  ('CY_BICEPS_CURL', '/machinefit/assets/machines/cybex/cy_biceps_curl.svg', '{"ko":"바이셉스 컬","en":"Biceps Curl"}'),
  ('CY_TRICEPS_EXTENSION', '/machinefit/assets/machines/cybex/cy_triceps_extension.svg', '{"ko":"트라이셉스 익스텐션","en":"Triceps Extension"}'),
  ('HS_ISO_LATERAL_HIGH_ROW', '/machinefit/assets/machines/hammer_strength/hs_iso_lateral_high_row.svg', '{"ko":"아이소 레터럴 하이 로우","en":"Iso-Lateral High Row"}'),
  ('HS_SELECTORIZED_CHEST_PRESS', '/machinefit/assets/machines/hammer_strength/hs_selectorized_chest_press.svg', '{"ko":"셀렉터라이즈드 체스트 프레스","en":"Selectorized Chest Press"}'),
  ('HS_LEG_EXTENSION', '/machinefit/assets/machines/hammer_strength/hs_leg_extension.svg', '{"ko":"레그 익스텐션","en":"Leg Extension"}'),
  ('HS_LEG_CURL', '/machinefit/assets/machines/hammer_strength/hs_leg_curl.svg', '{"ko":"레그 컬","en":"Leg Curl"}'),
  ('HS_SHOULDER_PRESS', '/machinefit/assets/machines/hammer_strength/hs_shoulder_press.svg', '{"ko":"숄더 프레스","en":"Shoulder Press"}'),
  ('HS_ISO_LATERAL_ROW', '/machinefit/assets/machines/hammer_strength/hs_iso_lateral_row.svg', '{"ko":"아이소 레터럴 로우","en":"Iso-Lateral Row"}'),
  ('HS_ISO_LATERAL_CHEST_PRESS', '/machinefit/assets/machines/hammer_strength/hs_iso_lateral_chest_press.svg', '{"ko":"아이소 레터럴 체스트 프레스","en":"Iso-Lateral Chest Press"}'),
  ('HS_LAT_PULLDOWN', '/machinefit/assets/machines/hammer_strength/hs_lat_pulldown.svg', '{"ko":"랫 풀다운","en":"Lat Pulldown"}'),
  ('HS_LEG_PRESS', '/machinefit/assets/machines/hammer_strength/hs_leg_press.svg', '{"ko":"레그 프레스","en":"Leg Press"}'),
  ('HS_PEC_FLY', '/machinefit/assets/machines/hammer_strength/hs_pec_fly.svg', '{"ko":"펙 플라이","en":"Pec Fly"}'),
  ('HS_BICEPS_CURL', '/machinefit/assets/machines/hammer_strength/hs_biceps_curl.svg', '{"ko":"바이셉스 컬","en":"Biceps Curl"}'),
  ('HS_TRICEPS_EXTENSION', '/machinefit/assets/machines/hammer_strength/hs_triceps_extension.svg', '{"ko":"트라이셉스 익스텐션","en":"Triceps Extension"}'),
  ('LF_CHEST_PRESS', '/machinefit/assets/machines/life_fitness/lf_chest_press.svg', '{"ko":"체스트 프레스","en":"Chest Press"}'),
  ('LF_SHOULDER_PRESS', '/machinefit/assets/machines/life_fitness/lf_shoulder_press.svg', '{"ko":"숄더 프레스","en":"Shoulder Press"}'),
  ('LF_LAT_PULLDOWN', '/machinefit/assets/machines/life_fitness/lf_lat_pulldown.svg', '{"ko":"랫 풀다운","en":"Lat Pulldown"}'),
  ('LF_SEATED_ROW', '/machinefit/assets/machines/life_fitness/lf_seated_row.svg', '{"ko":"시티드 로우","en":"Seated Row"}'),
  ('LF_LEG_PRESS', '/machinefit/assets/machines/life_fitness/lf_leg_press.svg', '{"ko":"레그 프레스","en":"Leg Press"}'),
  ('LF_LEG_EXTENSION', '/machinefit/assets/machines/life_fitness/lf_leg_extension.svg', '{"ko":"레그 익스텐션","en":"Leg Extension"}'),
  ('LF_LEG_CURL', '/machinefit/assets/machines/life_fitness/lf_leg_curl.svg', '{"ko":"레그 컬","en":"Leg Curl"}'),
  ('LF_PEC_FLY', '/machinefit/assets/machines/life_fitness/lf_pec_fly.svg', '{"ko":"펙 플라이","en":"Pec Fly"}'),
  ('LF_ABDOMINAL', '/machinefit/assets/machines/life_fitness/lf_abdominal.svg', '{"ko":"어브도미널","en":"Abdominal"}'),
  ('LF_BACK_EXTENSION', '/machinefit/assets/machines/life_fitness/lf_back_extension.svg', '{"ko":"백 익스텐션","en":"Back Extension"}'),
  ('LF_BICEPS_CURL', '/machinefit/assets/machines/life_fitness/lf_biceps_curl.svg', '{"ko":"바이셉스 컬","en":"Biceps Curl"}'),
  ('LF_TRICEPS_PRESS', '/machinefit/assets/machines/life_fitness/lf_triceps_press.svg', '{"ko":"트라이셉스 프레스","en":"Triceps Press"}'),
  ('TG_CHEST_PRESS', '/machinefit/assets/machines/technogym/tg_chest_press.svg', '{"ko":"체스트 프레스","en":"Chest Press"}'),
  ('TG_SHOULDER_PRESS', '/machinefit/assets/machines/technogym/tg_shoulder_press.svg', '{"ko":"숄더 프레스","en":"Shoulder Press"}'),
  ('TG_LAT_MACHINE', '/machinefit/assets/machines/technogym/tg_lat_machine.svg', '{"ko":"랫 머신","en":"Lat Machine"}'),
  ('TG_LOW_ROW', '/machinefit/assets/machines/technogym/tg_low_row.svg', '{"ko":"로우 로우","en":"Low Row"}'),
  ('TG_LEG_PRESS', '/machinefit/assets/machines/technogym/tg_leg_press.svg', '{"ko":"레그 프레스","en":"Leg Press"}'),
  ('TG_LEG_EXTENSION', '/machinefit/assets/machines/technogym/tg_leg_extension.svg', '{"ko":"레그 익스텐션","en":"Leg Extension"}'),
  ('TG_LEG_CURL', '/machinefit/assets/machines/technogym/tg_leg_curl.svg', '{"ko":"레그 컬","en":"Leg Curl"}'),
  ('TG_PEC_FLY', '/machinefit/assets/machines/technogym/tg_pec_fly.svg', '{"ko":"펙 플라이","en":"Pec Fly"}'),
  ('TG_ABDOMINAL', '/machinefit/assets/machines/technogym/tg_abdominal.svg', '{"ko":"어브도미널","en":"Abdominal"}'),
  ('TG_LOWER_BACK', '/machinefit/assets/machines/technogym/tg_lower_back.svg', '{"ko":"로워 백","en":"Lower Back"}'),
  ('TG_BICEPS_CURL', '/machinefit/assets/machines/technogym/tg_biceps_curl.svg', '{"ko":"바이셉스 컬","en":"Biceps Curl"}'),
  ('TG_TRICEPS_EXTENSION', '/machinefit/assets/machines/technogym/tg_triceps_extension.svg', '{"ko":"트라이셉스 익스텐션","en":"Triceps Extension"}')
) AS v(code, image_url, alt_text)
ON m.code = v.code
WHERE NOT EXISTS (
  SELECT 1 FROM machine_images mi
  WHERE mi.machine_id = m.id AND mi.is_primary = true
);

-- Refresh primary URL if a primary row already exists
UPDATE machine_images mi
SET image_url = v.image_url,
    alt_text = v.alt_text::jsonb,
    updated_at = NOW()
FROM machines m
JOIN (VALUES
  ('CY_CHEST_PRESS', '/machinefit/assets/machines/cybex/cy_chest_press.svg', '{"ko":"체스트 프레스","en":"Chest Press"}'),
  ('CY_SHOULDER_PRESS', '/machinefit/assets/machines/cybex/cy_shoulder_press.svg', '{"ko":"숄더 프레스","en":"Shoulder Press"}'),
  ('CY_LAT_PULLDOWN', '/machinefit/assets/machines/cybex/cy_lat_pulldown.svg', '{"ko":"랫 풀다운","en":"Lat Pulldown"}'),
  ('CY_SEATED_ROW', '/machinefit/assets/machines/cybex/cy_seated_row.svg', '{"ko":"시티드 로우","en":"Seated Row"}'),
  ('CY_LEG_PRESS', '/machinefit/assets/machines/cybex/cy_leg_press.svg', '{"ko":"레그 프레스","en":"Leg Press"}'),
  ('CY_LEG_EXTENSION', '/machinefit/assets/machines/cybex/cy_leg_extension.svg', '{"ko":"레그 익스텐션","en":"Leg Extension"}'),
  ('CY_LEG_CURL', '/machinefit/assets/machines/cybex/cy_leg_curl.svg', '{"ko":"레그 컬","en":"Leg Curl"}'),
  ('CY_PEC_FLY', '/machinefit/assets/machines/cybex/cy_pec_fly.svg', '{"ko":"펙 플라이","en":"Pec Fly"}'),
  ('CY_ABDOMINAL', '/machinefit/assets/machines/cybex/cy_abdominal.svg', '{"ko":"어브도미널","en":"Abdominal"}'),
  ('CY_BACK_EXTENSION', '/machinefit/assets/machines/cybex/cy_back_extension.svg', '{"ko":"백 익스텐션","en":"Back Extension"}'),
  ('CY_BICEPS_CURL', '/machinefit/assets/machines/cybex/cy_biceps_curl.svg', '{"ko":"바이셉스 컬","en":"Biceps Curl"}'),
  ('CY_TRICEPS_EXTENSION', '/machinefit/assets/machines/cybex/cy_triceps_extension.svg', '{"ko":"트라이셉스 익스텐션","en":"Triceps Extension"}'),
  ('HS_ISO_LATERAL_HIGH_ROW', '/machinefit/assets/machines/hammer_strength/hs_iso_lateral_high_row.svg', '{"ko":"아이소 레터럴 하이 로우","en":"Iso-Lateral High Row"}'),
  ('HS_SELECTORIZED_CHEST_PRESS', '/machinefit/assets/machines/hammer_strength/hs_selectorized_chest_press.svg', '{"ko":"셀렉터라이즈드 체스트 프레스","en":"Selectorized Chest Press"}'),
  ('HS_LEG_EXTENSION', '/machinefit/assets/machines/hammer_strength/hs_leg_extension.svg', '{"ko":"레그 익스텐션","en":"Leg Extension"}'),
  ('HS_LEG_CURL', '/machinefit/assets/machines/hammer_strength/hs_leg_curl.svg', '{"ko":"레그 컬","en":"Leg Curl"}'),
  ('HS_SHOULDER_PRESS', '/machinefit/assets/machines/hammer_strength/hs_shoulder_press.svg', '{"ko":"숄더 프레스","en":"Shoulder Press"}'),
  ('HS_ISO_LATERAL_ROW', '/machinefit/assets/machines/hammer_strength/hs_iso_lateral_row.svg', '{"ko":"아이소 레터럴 로우","en":"Iso-Lateral Row"}'),
  ('HS_ISO_LATERAL_CHEST_PRESS', '/machinefit/assets/machines/hammer_strength/hs_iso_lateral_chest_press.svg', '{"ko":"아이소 레터럴 체스트 프레스","en":"Iso-Lateral Chest Press"}'),
  ('HS_LAT_PULLDOWN', '/machinefit/assets/machines/hammer_strength/hs_lat_pulldown.svg', '{"ko":"랫 풀다운","en":"Lat Pulldown"}'),
  ('HS_LEG_PRESS', '/machinefit/assets/machines/hammer_strength/hs_leg_press.svg', '{"ko":"레그 프레스","en":"Leg Press"}'),
  ('HS_PEC_FLY', '/machinefit/assets/machines/hammer_strength/hs_pec_fly.svg', '{"ko":"펙 플라이","en":"Pec Fly"}'),
  ('HS_BICEPS_CURL', '/machinefit/assets/machines/hammer_strength/hs_biceps_curl.svg', '{"ko":"바이셉스 컬","en":"Biceps Curl"}'),
  ('HS_TRICEPS_EXTENSION', '/machinefit/assets/machines/hammer_strength/hs_triceps_extension.svg', '{"ko":"트라이셉스 익스텐션","en":"Triceps Extension"}'),
  ('LF_CHEST_PRESS', '/machinefit/assets/machines/life_fitness/lf_chest_press.svg', '{"ko":"체스트 프레스","en":"Chest Press"}'),
  ('LF_SHOULDER_PRESS', '/machinefit/assets/machines/life_fitness/lf_shoulder_press.svg', '{"ko":"숄더 프레스","en":"Shoulder Press"}'),
  ('LF_LAT_PULLDOWN', '/machinefit/assets/machines/life_fitness/lf_lat_pulldown.svg', '{"ko":"랫 풀다운","en":"Lat Pulldown"}'),
  ('LF_SEATED_ROW', '/machinefit/assets/machines/life_fitness/lf_seated_row.svg', '{"ko":"시티드 로우","en":"Seated Row"}'),
  ('LF_LEG_PRESS', '/machinefit/assets/machines/life_fitness/lf_leg_press.svg', '{"ko":"레그 프레스","en":"Leg Press"}'),
  ('LF_LEG_EXTENSION', '/machinefit/assets/machines/life_fitness/lf_leg_extension.svg', '{"ko":"레그 익스텐션","en":"Leg Extension"}'),
  ('LF_LEG_CURL', '/machinefit/assets/machines/life_fitness/lf_leg_curl.svg', '{"ko":"레그 컬","en":"Leg Curl"}'),
  ('LF_PEC_FLY', '/machinefit/assets/machines/life_fitness/lf_pec_fly.svg', '{"ko":"펙 플라이","en":"Pec Fly"}'),
  ('LF_ABDOMINAL', '/machinefit/assets/machines/life_fitness/lf_abdominal.svg', '{"ko":"어브도미널","en":"Abdominal"}'),
  ('LF_BACK_EXTENSION', '/machinefit/assets/machines/life_fitness/lf_back_extension.svg', '{"ko":"백 익스텐션","en":"Back Extension"}'),
  ('LF_BICEPS_CURL', '/machinefit/assets/machines/life_fitness/lf_biceps_curl.svg', '{"ko":"바이셉스 컬","en":"Biceps Curl"}'),
  ('LF_TRICEPS_PRESS', '/machinefit/assets/machines/life_fitness/lf_triceps_press.svg', '{"ko":"트라이셉스 프레스","en":"Triceps Press"}'),
  ('TG_CHEST_PRESS', '/machinefit/assets/machines/technogym/tg_chest_press.svg', '{"ko":"체스트 프레스","en":"Chest Press"}'),
  ('TG_SHOULDER_PRESS', '/machinefit/assets/machines/technogym/tg_shoulder_press.svg', '{"ko":"숄더 프레스","en":"Shoulder Press"}'),
  ('TG_LAT_MACHINE', '/machinefit/assets/machines/technogym/tg_lat_machine.svg', '{"ko":"랫 머신","en":"Lat Machine"}'),
  ('TG_LOW_ROW', '/machinefit/assets/machines/technogym/tg_low_row.svg', '{"ko":"로우 로우","en":"Low Row"}'),
  ('TG_LEG_PRESS', '/machinefit/assets/machines/technogym/tg_leg_press.svg', '{"ko":"레그 프레스","en":"Leg Press"}'),
  ('TG_LEG_EXTENSION', '/machinefit/assets/machines/technogym/tg_leg_extension.svg', '{"ko":"레그 익스텐션","en":"Leg Extension"}'),
  ('TG_LEG_CURL', '/machinefit/assets/machines/technogym/tg_leg_curl.svg', '{"ko":"레그 컬","en":"Leg Curl"}'),
  ('TG_PEC_FLY', '/machinefit/assets/machines/technogym/tg_pec_fly.svg', '{"ko":"펙 플라이","en":"Pec Fly"}'),
  ('TG_ABDOMINAL', '/machinefit/assets/machines/technogym/tg_abdominal.svg', '{"ko":"어브도미널","en":"Abdominal"}'),
  ('TG_LOWER_BACK', '/machinefit/assets/machines/technogym/tg_lower_back.svg', '{"ko":"로워 백","en":"Lower Back"}'),
  ('TG_BICEPS_CURL', '/machinefit/assets/machines/technogym/tg_biceps_curl.svg', '{"ko":"바이셉스 컬","en":"Biceps Curl"}'),
  ('TG_TRICEPS_EXTENSION', '/machinefit/assets/machines/technogym/tg_triceps_extension.svg', '{"ko":"트라이셉스 익스텐션","en":"Triceps Extension"}')
) AS v(code, image_url, alt_text) ON m.code = v.code
WHERE mi.machine_id = m.id AND mi.is_primary = true;
