-- Generated by database/scripts/build-catalog.mjs — do not edit by hand
-- Upserts brand logos, websites, and descriptions for catalog brands.

INSERT INTO brands (code, name, description, logo_url, website_url, is_active)
VALUES (
  'CYBEX',
  '{"ko":"사이벡스","en":"Cybex","ja":"サイベックス","zh":"赛百斯"}'::jsonb,
  '{"ko":"사이벡스는 인체공학적 설계와 명확한 조절 포인트로 알려진 머신 브랜드입니다. 관절 정렬을 세심하게 맞추기 쉬워, 목표 근육을 느끼면서도 불필요한 긴장을 줄이는 데 도움이 됩니다.","en":"Cybex is recognized for ergonomic machine design and clear adjustment points. Its equipment helps lifters align joints carefully, feel the target muscles, and reduce unnecessary strain during guided strength work."}'::jsonb,
  '/machinefit/assets/brands/cybex.svg',
  'https://www.cybexintl.com',
  true
)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  logo_url = EXCLUDED.logo_url,
  website_url = EXCLUDED.website_url,
  is_active = true,
  updated_at = NOW();

INSERT INTO brands (code, name, description, logo_url, website_url, is_active)
VALUES (
  'HAMMER_STRENGTH',
  '{"ko":"해머 스트렝스","en":"Hammer Strength","ja":"ハンマーストレングス","zh":"悍马力量"}'::jsonb,
  '{"ko":"해머 스트렝스는 플레이트 로디드와 아이소 레터럴 머신으로 잘 알려진 스트렝스 장비 브랜드입니다. 자연스러운 힘의 곡선과 좌우 독립 움직임을 강조해, 초보자부터 상급자까지 안정적으로 강한 수축을 연습할 수 있습니다.","en":"Hammer Strength is known for plate-loaded and iso-lateral strength machines that emphasize natural strength curves. The line supports stable, powerful training for beginners through advanced lifters while making left-right balance easier to notice."}'::jsonb,
  '/machinefit/assets/brands/hammer_strength.svg',
  'https://www.hammerstrength.com',
  true
)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  logo_url = EXCLUDED.logo_url,
  website_url = EXCLUDED.website_url,
  is_active = true,
  updated_at = NOW();

INSERT INTO brands (code, name, description, logo_url, website_url, is_active)
VALUES (
  'LIFE_FITNESS',
  '{"ko":"라이프 피트니스","en":"Life Fitness","ja":"ライフフィットネス","zh":"力健"}'::jsonb,
  '{"ko":"라이프 피트니스는 상업용 피트니스 센터에서 널리 쓰이는 글로벌 운동 장비 브랜드입니다. 부드러운 셀렉터라이즈드 저항과 직관적인 조절부가 특징이라, 처음 사용하는 사람도 자세를 차분히 익히기 좋습니다.","en":"Life Fitness is a global fitness equipment brand widely used in commercial gyms. Its selectorized machines are known for smooth resistance, intuitive adjustments, and approachable setup for steady technique practice."}'::jsonb,
  '/machinefit/assets/brands/life_fitness.svg',
  'https://www.lifefitness.com',
  true
)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  logo_url = EXCLUDED.logo_url,
  website_url = EXCLUDED.website_url,
  is_active = true,
  updated_at = NOW();

INSERT INTO brands (code, name, description, logo_url, website_url, is_active)
VALUES (
  'TECHNOGYM',
  '{"ko":"테크노짐","en":"Technogym","ja":"テクノジム","zh":"泰诺健"}'::jsonb,
  '{"ko":"테크노짐은 프리미엄 피트니스 시설에서 자주 만나는 이탈리아 기반 운동 장비 브랜드입니다. 세련된 디자인과 안정적인 가이드 동작이 특징이며, 일정한 리듬으로 근육 자극을 관리하기 좋습니다.","en":"Technogym is an Italian fitness equipment brand often found in premium training facilities. Its machines combine refined design with stable guided motion, making it easy to manage rhythm and muscle tension consistently."}'::jsonb,
  '/machinefit/assets/brands/technogym.svg',
  'https://www.technogym.com',
  true
)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  logo_url = EXCLUDED.logo_url,
  website_url = EXCLUDED.website_url,
  is_active = true,
  updated_at = NOW();
