-- Generated by database/scripts/build-catalog.mjs ??do not edit by hand
-- Upserts brand logos, websites, and descriptions for catalog brands.

INSERT INTO brands (code, name, description, logo_url, website_url, is_active)
VALUES (
  'CYBEX',
  '{"ko":"?ъ씠踰≪뒪","en":"Cybex","ja":"?듐궎?쇻긿??궧","zh":"壅쏁쇍??}'::jsonb,
  '{"ko":"?ъ씠踰≪뒪???몄껜怨듯븰???ㅺ퀎? 紐낇솗??議곗젅 ?ъ씤?몃줈 ?뚮젮吏?癒몄떊 釉뚮옖?쒖엯?덈떎. 愿???뺣젹???몄떖?섍쾶 留욎텛湲??ъ썙, 紐⑺몴 洹쇱쑁???먮겮硫댁꽌??遺덊븘?뷀븳 湲댁옣??以꾩씠?????꾩????⑸땲??","en":"Cybex is recognized for ergonomic machine design and clear adjustment points. Its equipment helps lifters align joints carefully, feel the target muscles, and reduce unnecessary strain during guided strength work."}'::jsonb,
  '/assets/brands/cybex.svg',
  'https://www.cybexintl.com',
  true
)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  logo_url = EXCLUDED.logo_url,
  website_url = EXCLUDED.website_url,
  is_active = true,
  updated_at = NOW();

INSERT INTO brands (code, name, description, logo_url, website_url, is_active)
VALUES (
  'HAMMER_STRENGTH',
  '{"ko":"?대㉧ ?ㅽ듃?앹뒪","en":"Hammer Strength","ja":"?뤵꺍?욁꺖?밤깉?с꺍?겹궧","zh":"?띺ß?쏃뇧"}'::jsonb,
  '{"ko":"?대㉧ ?ㅽ듃?앹뒪???뚮젅?댄듃 濡쒕뵒?쒖? ?꾩씠???덊꽣??癒몄떊?쇰줈 ???뚮젮吏??ㅽ듃?앹뒪 ?λ퉬 釉뚮옖?쒖엯?덈떎. ?먯뿰?ㅻ윭???섏쓽 怨≪꽑怨?醫뚯슦 ?낅┰ ?吏곸엫??媛뺤“?? 珥덈낫?먮????곴툒?먭퉴吏 ?덉젙?곸쑝濡?媛뺥븳 ?섏텞???곗뒿?????덉뒿?덈떎.","en":"Hammer Strength is known for plate-loaded and iso-lateral strength machines that emphasize natural strength curves. The line supports stable, powerful training for beginners through advanced lifters while making left-right balance easier to notice."}'::jsonb,
  '/assets/brands/hammer_strength.svg',
  'https://www.hammerstrength.com',
  true
)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  logo_url = EXCLUDED.logo_url,
  website_url = EXCLUDED.website_url,
  is_active = true,
  updated_at = NOW();

INSERT INTO brands (code, name, description, logo_url, website_url, is_active)
VALUES (
  'LIFE_FITNESS',
  '{"ko":"?쇱씠???쇳듃?덉뒪","en":"Life Fitness","ja":"?⒲궎?뺛깢?ｃ긿?덀깓??,"zh":"?쎾겈"}'::jsonb,
  '{"ko":"?쇱씠???쇳듃?덉뒪???곸뾽???쇳듃?덉뒪 ?쇳꽣?먯꽌 ?먮━ ?곗씠??湲濡쒕쾶 ?대룞 ?λ퉬 釉뚮옖?쒖엯?덈떎. 遺?쒕윭????됲꽣?쇱씠利덈뱶 ???낵 吏곴??곸씤 議곗젅遺媛 ?뱀쭠?대씪, 泥섏쓬 ?ъ슜?섎뒗 ?щ엺???먯꽭瑜?李⑤텇???듯엳湲?醫뗭뒿?덈떎.","en":"Life Fitness is a global fitness equipment brand widely used in commercial gyms. Its selectorized machines are known for smooth resistance, intuitive adjustments, and approachable setup for steady technique practice."}'::jsonb,
  '/assets/brands/life_fitness.svg',
  'https://www.lifefitness.com',
  true
)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  logo_url = EXCLUDED.logo_url,
  website_url = EXCLUDED.website_url,
  is_active = true,
  updated_at = NOW();

INSERT INTO brands (code, name, description, logo_url, website_url, is_active)
VALUES (
  'TECHNOGYM',
  '{"ko":"?뚰겕?몄쭚","en":"Technogym","ja":"?녴궚?롢궦??,"zh":"力계???}'::jsonb,
  '{"ko":"?뚰겕?몄쭚? ?꾨━誘몄뾼 ?쇳듃?덉뒪 ?쒖꽕?먯꽌 ?먯＜ 留뚮굹???댄깉由ъ븘 湲곕컲 ?대룞 ?λ퉬 釉뚮옖?쒖엯?덈떎. ?몃젴???붿옄?멸낵 ?덉젙?곸씤 媛?대뱶 ?숈옉???뱀쭠?대ŉ, ?쇱젙??由щ벉?쇰줈 洹쇱쑁 ?먭레??愿由ы븯湲?醫뗭뒿?덈떎.","en":"Technogym is an Italian fitness equipment brand often found in premium training facilities. Its machines combine refined design with stable guided motion, making it easy to manage rhythm and muscle tension consistently."}'::jsonb,
  '/assets/brands/technogym.svg',
  'https://www.technogym.com',
  true
)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  logo_url = EXCLUDED.logo_url,
  website_url = EXCLUDED.website_url,
  is_active = true,
  updated_at = NOW();
