export const MACHINE_CODES = {
  HS_ISO_LATERAL_HIGH_ROW: 'HS_ISO_LATERAL_HIGH_ROW',
  HS_SELECTORIZED_CHEST_PRESS: 'HS_SELECTORIZED_CHEST_PRESS',
  HS_LEG_EXTENSION: 'HS_LEG_EXTENSION',
  HS_LEG_CURL: 'HS_LEG_CURL',
  HS_SHOULDER_PRESS: 'HS_SHOULDER_PRESS',
  FW_DUMBBELL: 'FW_DUMBBELL',
  FW_BARBELL: 'FW_BARBELL',
  FW_SMITH: 'FW_SMITH',
  FW_CABLE: 'FW_CABLE',
  FW_KETTLEBELL: 'FW_KETTLEBELL',
  BW_PULL_UP: 'BW_PULL_UP',
  BW_CHIN_UP: 'BW_CHIN_UP',
  BW_DIPS: 'BW_DIPS',
  BW_PUSH_UP: 'BW_PUSH_UP',
  BW_SQUAT: 'BW_SQUAT',
  BW_LUNGE: 'BW_LUNGE',
  BW_BULGARIAN_SPLIT_SQUAT: 'BW_BULGARIAN_SPLIT_SQUAT',
} as const;

export type MachineCode = (typeof MACHINE_CODES)[keyof typeof MACHINE_CODES];

export const BRAND_CODES = {
  FREE_WEIGHT: 'FREE_WEIGHT',
  BODYWEIGHT: 'BODYWEIGHT',
  HAMMER_STRENGTH: 'HAMMER_STRENGTH',
  LIFE_FITNESS: 'LIFE_FITNESS',
  CYBEX: 'CYBEX',
  TECHNOGYM: 'TECHNOGYM',
} as const;

export type BrandCode = (typeof BRAND_CODES)[keyof typeof BRAND_CODES];
