export const MACHINE_CODES = {
  HS_ISO_LATERAL_HIGH_ROW: 'HS_ISO_LATERAL_HIGH_ROW',
  HS_SELECTORIZED_CHEST_PRESS: 'HS_SELECTORIZED_CHEST_PRESS',
  HS_LEG_EXTENSION: 'HS_LEG_EXTENSION',
  HS_LEG_CURL: 'HS_LEG_CURL',
  HS_SHOULDER_PRESS: 'HS_SHOULDER_PRESS',
} as const;

export type MachineCode = (typeof MACHINE_CODES)[keyof typeof MACHINE_CODES];

export const BRAND_CODES = {
  HAMMER_STRENGTH: 'HAMMER_STRENGTH',
  LIFE_FITNESS: 'LIFE_FITNESS',
  CYBEX: 'CYBEX',
  TECHNOGYM: 'TECHNOGYM',
} as const;

export type BrandCode = (typeof BRAND_CODES)[keyof typeof BRAND_CODES];
