/** Default seat / pad / foot / handle for MachineFit standard types (공통 머신). */
export interface StandardMachineFitPositions {
  seatPosition?: number;
  backPadPosition?: number;
  footPosition?: number;
  handlePosition?: number;
}

export const STANDARD_MACHINE_FIT_POSITIONS: Record<string, StandardMachineFitPositions> = {
  STD_CHEST_PRESS: { seatPosition: 4, handlePosition: 2 },
  STD_INCLINE_CHEST_PRESS: { seatPosition: 4, handlePosition: 2 },
  STD_DECLINE_CHEST_PRESS: { seatPosition: 4, handlePosition: 2 },
  STD_CONVERGING_CHEST_PRESS: { seatPosition: 4, handlePosition: 2 },
  STD_ISO_LATERAL_CHEST_PRESS: { seatPosition: 4, handlePosition: 2 },
  STD_PLATE_LOADED_CHEST_PRESS: { seatPosition: 4, handlePosition: 2 },
  STD_PEC_DECK: { seatPosition: 4, handlePosition: 2 },
  STD_FLY_MACHINE: { seatPosition: 4, handlePosition: 2 },
  STD_DIP_MACHINE: { seatPosition: 4, handlePosition: 2 },
  STD_ASSISTED_DIP: { seatPosition: 4, footPosition: 3, handlePosition: 2 },
  STD_SUPER_INCLINE_PRESS: { seatPosition: 4, handlePosition: 2 },

  STD_LAT_PULLDOWN: { seatPosition: 4, footPosition: 3 },
  STD_WIDE_LAT_PULLDOWN: { seatPosition: 4, footPosition: 3 },
  STD_FRONT_PULLDOWN: { seatPosition: 4, footPosition: 3 },
  STD_ISO_LATERAL_LAT_PULLDOWN: { seatPosition: 4, backPadPosition: 3, footPosition: 3 },
  STD_HIGH_ROW: { seatPosition: 4, backPadPosition: 3, footPosition: 3, handlePosition: 2 },
  STD_ISO_LATERAL_HIGH_ROW: { seatPosition: 4, backPadPosition: 3, footPosition: 3, handlePosition: 2 },
  STD_SEATED_ROW: { seatPosition: 4, backPadPosition: 3, footPosition: 3, handlePosition: 2 },
  STD_ROW_MACHINE: { seatPosition: 4, backPadPosition: 3, footPosition: 3, handlePosition: 2 },
  STD_LOW_ROW: { seatPosition: 4, backPadPosition: 3, footPosition: 3, handlePosition: 2 },
  STD_MID_ROW: { seatPosition: 4, backPadPosition: 3, footPosition: 3, handlePosition: 2 },
  STD_ISO_LATERAL_ROW: { seatPosition: 4, backPadPosition: 3, footPosition: 3, handlePosition: 2 },
  STD_ISO_LATERAL_LOW_ROW: { seatPosition: 4, backPadPosition: 3, footPosition: 3, handlePosition: 2 },
  STD_CHEST_SUPPORTED_ROW: { seatPosition: 4, backPadPosition: 4, footPosition: 3, handlePosition: 2 },
  STD_T_BAR_ROW: { seatPosition: 4, backPadPosition: 4, footPosition: 3, handlePosition: 2 },
  STD_PULLOVER: { seatPosition: 4, backPadPosition: 3, footPosition: 3, handlePosition: 2 },
  STD_ASSISTED_PULLUP: { seatPosition: 4, footPosition: 3, handlePosition: 2 },

  STD_SHOULDER_PRESS: { seatPosition: 4, backPadPosition: 4, handlePosition: 2 },
  STD_ISO_LATERAL_SHOULDER_PRESS: { seatPosition: 4, backPadPosition: 4, handlePosition: 2 },
  STD_PLATE_LOADED_SHOULDER_PRESS: { seatPosition: 4, backPadPosition: 4, handlePosition: 2 },
  STD_LATERAL_RAISE: { seatPosition: 4, handlePosition: 2 },
  STD_MACHINE_LATERAL_RAISE: { seatPosition: 4, handlePosition: 2 },
  STD_REAR_DELT: { seatPosition: 4, backPadPosition: 4, handlePosition: 2 },
  STD_REAR_DELT_REVERSE_PEC: { seatPosition: 4, backPadPosition: 4, handlePosition: 2 },
  STD_FRONT_RAISE: { seatPosition: 4, handlePosition: 2 },
  STD_UPRIGHT_ROW: { seatPosition: 4, backPadPosition: 3, handlePosition: 2 },
  STD_ROTATOR_MACHINE: { seatPosition: 4, backPadPosition: 3, handlePosition: 2 },
  STD_SHOULDER_LATERAL_COMBO: { seatPosition: 4, backPadPosition: 4, handlePosition: 2 },

  STD_LEG_PRESS: { backPadPosition: 3, footPosition: 4 },
  STD_45_LEG_PRESS: { backPadPosition: 3, footPosition: 4 },
  STD_HORIZONTAL_LEG_PRESS: { backPadPosition: 3, footPosition: 4 },
  STD_HACK_SQUAT: { backPadPosition: 3, footPosition: 4, handlePosition: 2 },
  STD_SQUAT_PRESS: { backPadPosition: 3, footPosition: 4, handlePosition: 2 },
  STD_BELT_SQUAT: { footPosition: 4, handlePosition: 2 },
  STD_LEG_EXTENSION: { seatPosition: 4, backPadPosition: 3, footPosition: 3 },
  STD_SEATED_LEG_CURL: { seatPosition: 4, backPadPosition: 3, footPosition: 3 },
  STD_LYING_LEG_CURL: { backPadPosition: 3, footPosition: 3 },
  STD_STANDING_LEG_CURL: { footPosition: 3, handlePosition: 2 },
  STD_SINGLE_LEG_CURL: { seatPosition: 4, backPadPosition: 3, footPosition: 3 },
  STD_HIP_THRUST: { seatPosition: 4, backPadPosition: 3, footPosition: 4, handlePosition: 2 },
  STD_GLUTE_DRIVE: { seatPosition: 4, backPadPosition: 3, footPosition: 4, handlePosition: 2 },
  STD_GLUTE_KICKBACK: { seatPosition: 4, footPosition: 4, handlePosition: 2 },
  STD_HIP_ABDUCTION: { seatPosition: 4, backPadPosition: 3, footPosition: 3, handlePosition: 2 },
  STD_HIP_ADDUCTION: { seatPosition: 4, backPadPosition: 3, footPosition: 3, handlePosition: 2 },
  STD_GLUTE_HIP_MACHINE: { seatPosition: 4, backPadPosition: 3, footPosition: 3, handlePosition: 2 },
  STD_STANDING_CALF: { footPosition: 4, handlePosition: 2 },
  STD_SEATED_CALF: { seatPosition: 4, backPadPosition: 3, footPosition: 4, handlePosition: 2 },
  STD_LEG_PRESS_CALF: { backPadPosition: 3, footPosition: 4 },

  STD_BICEPS_CURL: { seatPosition: 4, backPadPosition: 3, handlePosition: 2 },
  STD_PREACHER_CURL: { seatPosition: 4, backPadPosition: 3, footPosition: 3, handlePosition: 2 },
  STD_ISO_LATERAL_BICEPS_CURL: { seatPosition: 4, backPadPosition: 3, handlePosition: 2 },
  STD_ARM_CURL: { seatPosition: 4, backPadPosition: 3, handlePosition: 2 },
  STD_TRICEPS_EXTENSION: { seatPosition: 4, backPadPosition: 3, handlePosition: 2 },
  STD_TRICEPS_PRESS: { seatPosition: 4, backPadPosition: 3, handlePosition: 2 },
  STD_DIP_TRICEPS_MACHINE: { seatPosition: 4, backPadPosition: 3, handlePosition: 2 },
  STD_BICEPS_TRICEPS_COMBO: { seatPosition: 4, backPadPosition: 3, handlePosition: 2 },

  STD_AB_CRUNCH: { seatPosition: 4, backPadPosition: 3, footPosition: 3, handlePosition: 2 },
  STD_ABDOMINAL: { seatPosition: 4, backPadPosition: 3, footPosition: 3, handlePosition: 2 },
  STD_ROTARY_TORSO: { seatPosition: 4, backPadPosition: 3, footPosition: 3, handlePosition: 2 },
  STD_SIDE_BEND: { seatPosition: 4, backPadPosition: 3, footPosition: 3, handlePosition: 2 },
  STD_BACK_EXTENSION: { backPadPosition: 3, footPosition: 3, handlePosition: 2 },
  STD_HIP_EXTENSION: { seatPosition: 4, backPadPosition: 3, footPosition: 3, handlePosition: 2 },
  STD_ABS_BACK_COMBO: { seatPosition: 4, backPadPosition: 3, footPosition: 3, handlePosition: 2 },

  STD_CABLE_CROSSOVER: { handlePosition: 1 },
  STD_DUAL_ADJUSTABLE_PULLEY: { handlePosition: 1 },
  STD_MULTI_JUNGLE_GYM: { handlePosition: 1 },
  STD_ASSISTED_PULLUP_DIP: { seatPosition: 4, footPosition: 3, handlePosition: 2 },
  STD_SMITH_MACHINE: {},
  STD_POWER_RACK: {},
  STD_HALF_RACK: {},
};
