export const QUERY_KEYS = {
  machines: ['machines'] as const,
  machine: (code: string) => ['machines', code] as const,
  brands: ['brands'] as const,
  brand: (code: string) => ['brands', code] as const,
  gyms: ['gyms'] as const,
  gym: (id: string) => ['gyms', id] as const,
  recommendations: ['recommendations'] as const,
  favorites: ['favorites'] as const,
  history: ['history'] as const,
  historyList: (params?: { limit?: number }) =>
    ['history', 'list', params ?? {}] as const,
  historyForMachine: (machineCode: string) =>
    ['history', 'machine', machineCode] as const,
  posts: ['posts'] as const,
  machineRequests: ['machine-requests'] as const,
  ownerDashboard: ['owner', 'dashboard'] as const,
  ownerGyms: ['owner', 'gyms'] as const,
  notifications: ['notifications'] as const,
  notificationCount: ['notifications', 'unread'] as const,
  adminDashboard: ['admin', 'dashboard'] as const,
  adminUsers: ['admin', 'users'] as const,
  adminGyms: ['admin', 'gyms'] as const,
  adminMachines: ['admin', 'machines'] as const,
  adminModeration: ['admin', 'moderation'] as const,
  user: ['user', 'me'] as const,
} as const;
