-- Replace 공통 머신 주의사항 / 사용팁 with the canonical 80-type copy.
-- Overwrites existing catalog, settings, and recommendation snapshots for linked machines.

ALTER TABLE standard_machine_types
  ADD COLUMN IF NOT EXISTS tips JSONB,
  ADD COLUMN IF NOT EXISTS warnings JSONB;

COMMENT ON COLUMN standard_machine_types.tips IS
  'Canonical 사용팁 {ko:[],en:[]}. Replaces brand-specific copy on linked machines.';
COMMENT ON COLUMN standard_machine_types.warnings IS
  'Canonical 주의사항 {ko:[],en:[]}. Replaces brand-specific copy on linked machines.';

UPDATE standard_machine_types AS t SET
  tips = v.tips,
  warnings = v.warnings,
  updated_at = NOW()
FROM (VALUES
  ('STD_45_LEG_PRESS', '{"ko":["발판 중앙에 안정적으로 발을 둔다.","무릎과 발끝 방향을 맞춘다.","내려오는 깊이를 통제한다.","발 전체로 밀어낸다.","무게를 튕기지 않는다.","큐잉: “깊이보다 골반 위치가 무너지지 않는 범위를 먼저 잡으세요.”"],"en":["Place your feet securely on the platform.","Align knees with toes.","Control the depth.","Press through the whole foot.","Do not bounce the weight.","Cue: “Prioritize keeping your pelvis stable over going deeper.”"]}'::jsonb, '{"ko":["골반이 말려 올라가는 깊이까지 내려가지 않는다.","무릎을 강하게 잠그지 않는다.","발 위치가 불안정하지 않게 한다."],"en":["Do not descend so far that the pelvis rolls excessively.","Do not forcefully lock the knees.","Keep the feet stable."]}'::jsonb),
  ('STD_ABDOMINAL', '{"ko":["복부에 힘을 준다.","몸통을 앞으로 말아준다.","골반을 안정적으로 둔다.","끝에서 복부를 조인다.","천천히 돌아온다.","큐잉: “머리를 숙이는 게 아니라 명치와 골반을 가까이 만든다고 생각하세요.”"],"en":["Brace the abdomen.","Curl the torso forward.","Keep the pelvis stable.","Squeeze the abs at the end.","Return slowly.","Cue: “Think about bringing your ribcage toward your pelvis rather than simply lowering your head.”"]}'::jsonb, '{"ko":["머리와 목을 억지로 당기지 않는다.","허리 반동을 사용하지 않는다.","너무 무거운 무게를 사용하지 않는다."],"en":["Do not pull the head or neck.","Do not use lower-back momentum.","Do not use excessive resistance."]}'::jsonb),
  ('STD_ABS_BACK_COMBO', '{"ko":["복근에서는 갈비뼈를 골반 쪽으로 말아준다.","허리에서는 엉덩이에서 몸통을 펴준다.","각 동작의 패드 위치를 확인한다.","반동 없이 움직인다.","통제된 범위를 사용한다.","큐잉: “복근은 몸통을 말고, 허리는 엉덩이에서 몸통을 펴는 데 집중하세요.”"],"en":["Curl the ribcage toward the pelvis for abdominal work.","Extend from the hips for back work.","Check the pad position for each exercise.","Move without momentum.","Use a controlled range.","Cue: “Curl the torso for abs and extend from the hips for back work.”"]}'::jsonb, '{"ko":["복근과 허리 동작의 설정을 각각 확인한다.","허리 동작에서 과하게 젖히지 않는다.","복근 동작에서 목으로 당기지 않는다."],"en":["Check the setup for each movement separately.","Do not excessively extend the lower back.","Do not pull with the neck during abdominal work."]}'::jsonb),
  ('STD_AB_CRUNCH', '{"ko":["패드 위치를 몸에 맞춘다.","갈비뼈와 골반을 가까워지게 만든다는 느낌으로 접는다.","배에 힘을 유지한다.","끝에서 잠깐 멈춘다.","천천히 돌아온다.","큐잉: “목으로 숙이지 말고 갈비뼈를 골반 쪽으로 말아주세요.”"],"en":["Adjust the pad to fit your body.","Think about bringing the ribs toward the pelvis.","Keep the abdomen engaged.","Pause briefly at the end.","Return slowly.","Cue: “Do not bend from the neck; curl your ribs toward your pelvis.”"]}'::jsonb, '{"ko":["허리를 과하게 꺾어 시작하지 않는다.","목을 당겨 몸을 접지 않는다.","무게를 튕겨 사용하지 않는다."],"en":["Do not excessively arch the lower back.","Do not pull with the neck.","Do not use momentum."]}'::jsonb),
  ('STD_ARM_CURL', '{"ko":["팔꿈치를 안정시킨다.","손잡이를 몸쪽으로 당긴다.","위에서 이두근을 조인다.","천천히 내려온다.","어깨가 올라가지 않게 한다.","큐잉: “어깨는 그대로 두고 팔꿈치 아래만 접는다고 생각하세요.”"],"en":["Stabilize the elbows.","Curl the handle toward the body.","Squeeze the biceps at the top.","Lower slowly.","Keep the shoulders down.","Cue: “Keep the shoulders still and curl only below the elbow.”"]}'::jsonb, '{"ko":["팔꿈치 위치를 패드에 맞춘다.","몸통으로 무게를 들어 올리지 않는다.","손목을 과하게 꺾지 않는다."],"en":["Position the elbows correctly on the pad.","Do not use the torso to lift the weight.","Do not excessively bend the wrists."]}'::jsonb),
  ('STD_ASSISTED_DIP', '{"ko":["손잡이를 잡고 몸을 안정시킨다.","팔꿈치를 뒤쪽으로 보낸다.","손잡이를 아래로 밀어 올라온다.","내려올 때 속도를 조절한다.","보조가 부족하면 무게를 조절한다.","큐잉: “무릎으로 올라오지 말고 손잡이를 아래로 눌러 몸을 올려주세요.”"],"en":["Grip the handles and stabilize yourself.","Let the elbows move backward.","Press the handles down to rise.","Control the descent.","Increase assistance if needed.","Cue: “Press the handles down to raise your body rather than pushing with your knees.”"]}'::jsonb, '{"ko":["보조 무게를 확인한다.","움직이는 발판과 패드에 손발이 끼지 않게 한다.","패드 위에서 몸이 흔들리지 않게 한다."],"en":["Check the assistance resistance.","Keep hands and feet clear of moving platforms.","Stay stable on the platform."]}'::jsonb),
  ('STD_ASSISTED_PULLUP', '{"ko":["가슴을 살짝 들어준다.","팔꿈치를 아래로 당긴다.","몸을 위로 끌어올린다.","내려오는 속도를 조절한다.","턱보다 팔꿈치 움직임에 집중한다.","큐잉: “턱을 올리려 하지 말고 팔꿈치를 바닥으로 끌어내려 몸을 올리세요.”"],"en":["Lift the chest slightly.","Drive the elbows down.","Pull the body upward.","Control the descent.","Focus on elbow movement rather than the chin.","Cue: “Drive your elbows down to lift your body rather than chasing your chin over the bar.”"]}'::jsonb, '{"ko":["보조 패드에 안정적으로 올라간다.","내려올 때 몸이 떨어지지 않게 한다.","어깨가 아픈 범위까지 억지로 당기지 않는다."],"en":["Stabilize yourself on the assistance platform.","Do not drop suddenly.","Do not force a painful shoulder range."]}'::jsonb),
  ('STD_ASSISTED_PULLUP_DIP', '{"ko":["풀업에서는 팔꿈치를 아래로 당긴다.","딥에서는 손잡이를 아래로 민다.","몸통을 통제한다.","내려오는 속도를 조절한다.","보조량을 운동 수준에 맞춘다.","큐잉: “풀업은 팔꿈치를 아래로, 딥은 손잡이를 아래로 밀어주세요.”"],"en":["For pull-ups, drive the elbows down.","For dips, press the handles down.","Control the torso.","Control the descent.","Set assistance appropriate to your ability.","Cue: “Drive your elbows down for pull-ups and press the handles down for dips.”"]}'::jsonb, '{"ko":["보조 무게와 패드 위치를 확인한다.","움직이는 패드에 손발이 끼지 않게 한다.","내려올 때 패드에 몸을 안정적으로 유지한다."],"en":["Check the assistance resistance and platform.","Keep hands and feet clear of moving parts.","Stay stable on the platform during descent."]}'::jsonb),
  ('STD_BACK_EXTENSION', '{"ko":["골반을 안정적으로 고정한다.","몸통을 엉덩이에서 펴는 느낌으로 올라온다.","허리를 뒤로 꺾는 데 집중하지 않는다.","위에서 몸통을 중립으로 멈춘다.","천천히 내려온다.","큐잉: “허리를 꺾어 올라오지 말고 엉덩이에서 몸통을 펴주세요.”"],"en":["Stabilize the pelvis.","Extend from the hips.","Do not focus on bending the lower back backward.","Stop at a neutral torso position.","Lower slowly.","Cue: “Extend your torso from the hips rather than arching your lower back.”"]}'::jsonb, '{"ko":["허리를 과하게 젖히지 않는다.","패드 위치가 골반을 안정적으로 지지하는지 확인한다.","반동으로 몸을 세우지 않는다."],"en":["Do not excessively hyperextend the lower back.","Make sure the pad supports the pelvis appropriately.","Do not use momentum."]}'::jsonb),
  ('STD_BELT_SQUAT', '{"ko":["발을 안정적으로 둔다.","엉덩이를 아래로 내린다.","무릎과 발끝 방향을 맞춘다.","발 전체로 밀어 올라온다.","상체를 억지로 세우려 하지 않는다.","큐잉: “상체보다 골반을 아래로 내리고 발바닥 전체로 올라오세요.”"],"en":["Keep the feet stable.","Lower the hips.","Align knees with toes.","Drive up through the whole foot.","Do not force the torso upright.","Cue: “Lower your hips and drive back up through your whole foot.”"]}'::jsonb, '{"ko":["벨트가 골반에 안정적으로 걸렸는지 확인한다.","안전장치를 확인한다.","무게가 너무 무거워 몸이 끌려가지 않게 한다."],"en":["Make sure the belt is securely positioned around the hips.","Check the safety mechanism.","Avoid weight that pulls you out of position."]}'::jsonb),
  ('STD_BICEPS_CURL', '{"ko":["팔꿈치를 안정적으로 둔다.","손잡이를 어깨 쪽으로 당긴다.","위에서 이두근을 조인다.","내려올 때 천천히 편다.","어깨가 따라 움직이지 않게 한다.","큐잉: “팔꿈치는 그대로 두고 손잡이를 어깨 쪽으로 끌어오세요.”"],"en":["Keep the elbows stable.","Curl the handle toward the shoulders.","Squeeze the biceps at the top.","Lower slowly.","Keep the shoulders from taking over.","Cue: “Keep your elbows still and curl the handle toward your shoulders.”"]}'::jsonb, '{"ko":["팔꿈치를 지나치게 앞뒤로 움직이지 않는다.","몸을 뒤로 젖혀 반동을 만들지 않는다.","손목을 심하게 꺾지 않는다."],"en":["Do not move the elbows excessively.","Do not lean back for momentum.","Do not excessively bend the wrists."]}'::jsonb),
  ('STD_BICEPS_TRICEPS_COMBO', '{"ko":["바이셉스는 팔꿈치를 안정시킨다.","트라이셉스는 팔꿈치를 안정시킨다.","양쪽 팔을 비슷한 속도로 움직인다.","끝에서 해당 근육을 조인다.","천천히 돌아온다.","큐잉: “팔꿈치 위치를 고정하고 팔꿈치 아래만 움직인다고 생각하세요.”"],"en":["Stabilize the elbows for biceps work.","Stabilize the elbows for triceps work.","Move both arms at a similar speed.","Squeeze the target muscle at the end.","Return slowly.","Cue: “Keep the elbows fixed and move only below the elbows.”"]}'::jsonb, '{"ko":["선택한 운동의 패드와 손잡이를 맞춘다.","운동 중 다른 동작의 위치로 바꾸지 않는다.","무게 때문에 몸통을 흔들지 않는다."],"en":["Set the pads and handles for the selected exercise.","Do not change setup during the movement.","Do not swing the torso."]}'::jsonb),
  ('STD_CABLE_CROSSOVER', '{"ko":["발을 안정적으로 벌린다.","가슴 운동에서는 팔꿈치를 앞쪽으로 모은다.","어깨를 과하게 앞으로 밀지 않는다.","케이블을 놓지 않고 천천히 돌아온다.","좌우 높이를 맞춘다.","큐잉: “손잡이를 모으기보다 양쪽 팔꿈치가 앞에서 가까워진다고 생각하세요.”"],"en":["Set a stable stance.","For chest work, bring the elbows forward.","Do not excessively push the shoulders forward.","Return slowly while maintaining control.","Match both cable heights.","Cue: “Think about bringing your elbows toward each other rather than simply bringing the handles together.”"]}'::jsonb, '{"ko":["케이블과 손잡이가 제대로 연결됐는지 확인한다.","무게 때문에 몸이 앞으로 끌려가지 않게 한다.","케이블이 지나가는 경로에 다른 사람이 없는지 확인한다."],"en":["Check that the cables and handles are properly attached.","Do not let the resistance pull you forward.","Make sure nobody is in the cable path."]}'::jsonb),
  ('STD_CHEST_PRESS', '{"ko":["발을 바닥에 안정적으로 둔다.","가슴을 편안하게 세우고 시작한다.","손보다 팔꿈치를 앞쪽으로 보낸다는 느낌으로 민다.","끝에서 어깨를 앞으로 과하게 밀지 않는다.","천천히 시작 위치로 돌아온다.","큐잉: “손잡이를 미는 것보다 팔꿈치를 앞쪽으로 보내주세요.”"],"en":["Keep your feet stable on the floor.","Start with your chest comfortably upright.","Think about driving your elbows forward.","Do not excessively push your shoulders forward at the end.","Return slowly to the starting position.","Cue: “Drive your elbows forward rather than simply pushing the handles.”"]}'::jsonb, '{"ko":["시트를 조절해 손잡이가 가슴 중간 높이에 오도록 한다.","시작 위치에서 어깨가 과하게 뒤로 당겨지지 않게 한다.","무게 때문에 몸이 흔들리면 중량을 낮춘다."],"en":["Set the seat so the handles are around mid-chest height.","Do not let the starting position excessively pull the shoulders backward.","Reduce the weight if it makes your body unstable."]}'::jsonb),
  ('STD_CHEST_SUPPORTED_ROW', '{"ko":["가슴을 패드에 편하게 둔다.","팔꿈치를 뒤로 당긴다.","손보다 팔꿈치에 집중한다.","끝에서 등을 조인다.","천천히 돌아온다.","큐잉: “가슴은 패드에 그대로 두고 팔꿈치만 뒤로 보내세요.”"],"en":["Keep the chest comfortably against the pad.","Drive the elbows backward.","Focus on the elbows.","Squeeze the back.","Return slowly.","Cue: “Keep your chest on the pad and drive only your elbows backward.”"]}'::jsonb, '{"ko":["가슴 패드에 몸을 안정적으로 둔다.","몸을 패드에서 들어 반동을 만들지 않는다.","팔꿈치를 지나치게 뒤로 보내지 않는다."],"en":["Keep the chest firmly supported.","Do not lift away from the pad for momentum.","Do not drive the elbows excessively far back."]}'::jsonb),
  ('STD_CONVERGING_CHEST_PRESS', '{"ko":["가슴을 편안하게 세운다.","양쪽 팔꿈치를 앞쪽으로 보낸다.","손잡이가 자연스럽게 가운데로 가까워지게 한다.","마지막에 어깨를 앞으로 밀지 않는다.","돌아올 때도 천천히 움직인다.","큐잉: “손잡이를 모으기보다 양쪽 팔꿈치를 앞에서 가까이 만나게 해주세요.”"],"en":["Keep the chest comfortably upright.","Drive both elbows forward.","Allow the handles to naturally converge.","Do not shove the shoulders forward at the end.","Return slowly.","Cue: “Bring your elbows toward each other rather than simply bringing the handles together.”"]}'::jsonb, '{"ko":["시작 위치에서 어깨가 과하게 당겨지지 않게 한다.","양쪽 어깨가 한쪽으로 돌아가지 않게 한다.","손잡이가 빠르게 닫히지 않도록 통제한다."],"en":["Avoid excessive shoulder stretch at the start.","Do not let either shoulder rotate excessively.","Control the handles so they do not slam together."]}'::jsonb),
  ('STD_DECLINE_CHEST_PRESS', '{"ko":["발을 안정적으로 둔다.","가슴을 편안하게 유지한다.","팔꿈치를 앞쪽 아래로 보낸다.","돌아올 때 무게를 통제한다.","반동을 사용하지 않는다.","큐잉: “팔꿈치를 앞쪽 아래로 보내면서 밀어주세요.”"],"en":["Keep your feet stable.","Keep the chest comfortably upright.","Drive the elbows forward and slightly downward.","Control the return.","Avoid momentum.","Cue: “Drive your elbows forward and slightly down.”"]}'::jsonb, '{"ko":["손잡이가 가슴 아래쪽에 자연스럽게 맞도록 한다.","허리를 과하게 띄워 밀지 않는다.","어깨가 앞으로 끌려가지 않게 한다."],"en":["Align the handles naturally with the lower chest.","Do not excessively lift the lower back.","Do not let the shoulders get pulled forward."]}'::jsonb),
  ('STD_DIP_MACHINE', '{"ko":["발을 안정적으로 둔다.","가슴을 사용하려면 상체를 약간 앞으로 기울일 수 있다.","팔꿈치를 뒤쪽으로 보내며 내려간다.","손잡이를 아래로 밀며 올라온다.","편안한 깊이에서 방향을 바꾼다.","큐잉: “어깨부터 떨어뜨리지 말고 팔꿈치를 뒤로 보내며 내려가세요.”"],"en":["Keep your feet stable.","A slight forward lean can increase chest involvement.","Let the elbows move backward as you lower.","Press the handles down as you rise.","Reverse at a comfortable depth.","Cue: “Do not drop your shoulders first; let your elbows move back as you lower.”"]}'::jsonb, '{"ko":["손잡이 위치가 어깨에 편안한지 확인한다.","내려갈 때 어깨가 과하게 밀리지 않게 한다.","반동으로 올라오지 않는다."],"en":["Make sure the handles feel comfortable for your shoulders.","Do not let the shoulders drop excessively.","Do not use momentum."]}'::jsonb),
  ('STD_DIP_TRICEPS_MACHINE', '{"ko":["삼두 중심이면 몸통을 비교적 세운다.","팔꿈치를 뒤쪽으로 보낸다.","손잡이를 아래로 밀어 올라온다.","내려오는 구간을 통제한다.","어깨 위치를 유지한다.","큐잉: “몸을 앞으로 던지지 말고 팔꿈치를 뒤로 접었다가 아래로 밀어주세요.”"],"en":["Keep the torso relatively upright for triceps emphasis.","Let the elbows move backward.","Press the handles down to rise.","Control the descent.","Maintain shoulder position.","Cue: “Keep your torso controlled, bend the elbows back, then press down.”"]}'::jsonb, '{"ko":["선택한 동작의 손잡이 위치를 확인한다.","어깨가 불편한 깊이까지 내려가지 않는다.","반동을 사용하지 않는다."],"en":["Check the handle position for the selected movement.","Do not descend into an uncomfortable shoulder position.","Do not use momentum."]}'::jsonb),
  ('STD_DUAL_ADJUSTABLE_PULLEY', '{"ko":["운동 목적에 맞게 풀리 높이를 조절한다.","발을 안정적으로 둔다.","몸통을 통제한다.","케이블을 놓을 때도 천천히 돌아온다.","좌우 중량과 높이를 확인한다.","큐잉: “케이블보다 내가 움직이려는 팔꿈치의 방향을 먼저 생각하세요.”"],"en":["Set pulley height for the exercise.","Keep a stable stance.","Control the torso.","Return the cable slowly.","Check both sides for equal resistance and height.","Cue: “Think about the direction of your working elbow before thinking about the cable.”"]}'::jsonb, '{"ko":["양쪽 풀리 높이가 원하는 동작에 맞는지 확인한다.","케이블과 손잡이가 제대로 연결됐는지 확인한다.","움직이는 케이블 경로에 사람이 없는지 확인한다."],"en":["Check both pulley heights.","Check the cable and handle connections.","Keep people clear of the cable path."]}'::jsonb),
  ('STD_FLY_MACHINE', '{"ko":["몸통을 안정시킨다.","가슴을 편안하게 세운다.","팔꿈치를 앞쪽으로 보낸다.","모은 지점에서 잠깐 멈춘다.","천천히 벌어진다.","큐잉: “어깨를 앞으로 밀지 말고 팔꿈치만 앞에서 모아주세요.”"],"en":["Stabilize your torso.","Keep the chest comfortably upright.","Drive the elbows forward.","Pause briefly when the arms come together.","Return slowly.","Cue: “Keep your shoulders stable and bring your elbows together.”"]}'::jsonb, '{"ko":["시작 위치에서 어깨가 과하게 늘어나지 않게 한다.","팔꿈치를 과하게 잠그지 않는다.","반동으로 팔을 모으지 않는다."],"en":["Avoid excessive shoulder stretch at the start.","Do not forcefully lock the elbows.","Do not use momentum."]}'::jsonb),
  ('STD_FRONT_PULLDOWN', '{"ko":["가슴을 세운다.","바를 가슴 위쪽으로 당긴다.","팔꿈치를 아래로 보낸다.","내려온 지점에서 등을 유지한다.","천천히 올린다.","큐잉: “가슴을 바에 가져가지 말고 팔꿈치를 아래로 끌어내리세요.”"],"en":["Keep the chest up.","Pull toward the upper chest.","Drive the elbows down.","Maintain back tension at the bottom.","Return slowly.","Cue: “Drive your elbows down instead of bringing your chest toward the bar.”"]}'::jsonb, '{"ko":["바를 목 뒤로 넘기지 않는다.","허리를 과하게 젖히지 않는다.","팔꿈치를 억지로 뒤로 보내지 않는다."],"en":["Do not pull the bar behind the neck.","Do not excessively lean back.","Do not force the elbows excessively backward."]}'::jsonb),
  ('STD_FRONT_RAISE', '{"ko":["몸통을 고정한다.","팔을 앞쪽으로 들어 올린다.","어깨를 으쓱하지 않는다.","일정한 속도로 움직인다.","천천히 내린다.","큐잉: “몸을 뒤로 젖히지 말고 팔을 앞쪽으로 길게 보내주세요.”"],"en":["Stabilize the torso.","Raise the arms forward.","Do not shrug.","Move at a steady speed.","Lower slowly.","Cue: “Keep your torso still and reach your arms forward.”"]}'::jsonb, '{"ko":["몸을 뒤로 젖히지 않는다.","통증이 생기는 높이까지 올리지 않는다.","반동을 사용하지 않는다."],"en":["Do not lean backward.","Do not raise into a painful range.","Do not use momentum."]}'::jsonb),
  ('STD_GLUTE_DRIVE', '{"ko":["발을 안정적으로 둔다.","골반을 앞으로 밀어 올린다.","무릎 방향을 발끝과 맞춘다.","위에서 엉덩이를 조인다.","천천히 내려온다.","큐잉: “가슴을 들어 올리는 게 아니라 골반을 앞으로 밀어 엉덩이를 조여주세요.”"],"en":["Keep the feet stable.","Drive the hips forward and up.","Keep knees aligned with toes.","Squeeze the glutes at the top.","Lower under control.","Cue: “Drive the hips forward and squeeze the glutes rather than lifting the chest.”"]}'::jsonb, '{"ko":["패드가 골반에 안정적으로 닿는지 확인한다.","허리로 밀어 올리지 않는다.","무게가 몸을 끌어당기지 않게 한다."],"en":["Make sure the pad is secure against the hips.","Do not drive the movement with the lower back.","Do not let the load pull you out of position."]}'::jsonb),
  ('STD_GLUTE_HIP_MACHINE', '{"ko":["킥백은 발뒤꿈치를 뒤로 보낸다.","어브덕션은 무릎을 바깥으로 보낸다.","몸통은 안정적으로 유지한다.","끝에서 엉덩이를 조인다.","천천히 돌아온다.","큐잉: “허리로 움직이지 말고 골반 아래에서 다리를 움직여주세요.”"],"en":["For kickbacks, drive the heel backward.","For abduction, drive the knee outward.","Keep the torso stable.","Squeeze the glute at the end.","Return slowly.","Cue: “Move the leg from the hip rather than creating movement with your lower back.”"]}'::jsonb, '{"ko":["선택한 동작에 맞게 패드와 몸 위치를 맞춘다.","허리 반동을 사용하지 않는다.","골반이 돌아가지 않게 한다."],"en":["Set the pads and body position for the selected movement.","Do not use lower-back momentum.","Keep the pelvis stable."]}'::jsonb),
  ('STD_GLUTE_KICKBACK', '{"ko":["몸통을 안정시킨다.","발뒤꿈치를 뒤쪽으로 민다.","골반은 정면을 유지한다.","끝에서 엉덩이를 조인다.","천천히 돌아온다.","큐잉: “다리를 높이 올리지 말고 발뒤꿈치를 뒤쪽으로 길게 밀어주세요.”"],"en":["Stabilize the torso.","Drive the heel backward.","Keep the pelvis facing forward.","Squeeze the glute at the end.","Return slowly.","Cue: “Don’t chase height; drive your heel backward.”"]}'::jsonb, '{"ko":["허리를 꺾어 다리를 높이 올리지 않는다.","골반을 한쪽으로 돌리지 않는다.","지지하는 다리를 불안정하게 두지 않는다."],"en":["Do not arch the lower back to lift the leg higher.","Do not rotate the pelvis.","Keep the supporting leg stable."]}'::jsonb),
  ('STD_HACK_SQUAT', '{"ko":["발을 편안한 위치에 둔다.","엉덩이를 뒤·아래로 내린다.","발 전체로 바닥을 민다.","무릎과 발끝 방향을 맞춘다.","올라올 때 무릎을 튕기지 않는다.","큐잉: “발판을 아래로 미는 게 아니라 바닥을 발 전체로 밀어낸다고 생각하세요.”"],"en":["Place the feet comfortably.","Lower the hips down and back.","Push through the whole foot.","Keep knees aligned with toes.","Do not snap the knees at the top.","Cue: “Think about pushing the floor away through your whole foot.”"]}'::jsonb, '{"ko":["어깨와 등을 패드에 안정적으로 둔다.","무릎이 안쪽으로 무너지지 않게 한다.","안전장치를 해제·잠글 때 위치를 확인한다."],"en":["Keep the shoulders and back stable against the pads.","Do not let the knees collapse inward.","Check the safety mechanism before and after the set."]}'::jsonb),
  ('STD_HALF_RACK', '{"ko":["운동 시작 전에 바의 높이를 맞춘다.","스쿼트에서는 안전바를 적절한 높이에 둔다.","몸통과 발 위치를 안정적으로 잡는다.","반동보다 통제된 움직임을 사용한다.","운동이 끝나면 바를 확실히 걸어둔다.","큐잉: “중량을 올리는 것보다 먼저 안전바와 시작 높이를 맞춰주세요.”"],"en":["Set the bar height before starting.","Set the safety bars appropriately for squats.","Establish a stable torso and foot position.","Use controlled movement rather than momentum.","Re-rack the bar securely.","Cue: “Set the safety bars and starting height before adding more weight.”"]}'::jsonb, '{"ko":["J컵과 안전바 높이를 확인한다.","좌우 원판을 균형 있게 장착한다.","무리한 중량을 혼자 수행하지 않는다."],"en":["Check the J-cups and safety bars.","Load both sides evenly.","Do not attempt excessive weight alone."]}'::jsonb),
  ('STD_HIGH_ROW', '{"ko":["가슴을 연다.","어깨를 아래로 둔다.","팔꿈치를 뒤로 당긴다.","끝에서 등을 조인다.","천천히 돌아온다.","큐잉: “손잡이가 아니라 팔꿈치를 뒤로 보낸다고 생각하세요.”"],"en":["Open the chest.","Keep the shoulders down.","Drive the elbows back.","Squeeze the back at the end.","Return slowly.","Cue: “Think about driving your elbows backward, not just pulling the handles.”"]}'::jsonb, '{"ko":["몸통을 안정시킨다.","허리를 뒤로 젖혀 당기지 않는다.","팔꿈치를 지나치게 뒤로 보내지 않는다."],"en":["Stabilize the torso.","Do not lean back to pull.","Do not drive the elbows excessively far back."]}'::jsonb),
  ('STD_HIP_ABDUCTION', '{"ko":["골반을 안정시킨다.","무릎을 바깥쪽으로 보낸다.","상체를 과하게 움직이지 않는다.","끝에서 엉덩이 옆쪽을 조인다.","천천히 돌아온다.","큐잉: “발을 벌린다고 생각하지 말고 무릎으로 양옆을 밀어주세요.”"],"en":["Stabilize the pelvis.","Drive the knees outward.","Keep the torso stable.","Squeeze the outer glutes at the end.","Return slowly.","Cue: “Think about pushing your knees outward rather than moving your feet.”"]}'::jsonb, '{"ko":["골반을 좌우로 흔들지 않는다.","다리를 억지로 크게 벌리지 않는다.","반동으로 패드를 벌리지 않는다."],"en":["Do not rock the pelvis.","Do not force a large range.","Do not use momentum."]}'::jsonb),
  ('STD_HIP_ADDUCTION', '{"ko":["허리를 편안하게 둔다.","허벅지를 안쪽으로 모은다.","끝에서 잠깐 멈춘다.","돌아갈 때 천천히 벌어진다.","골반이 움직이지 않게 한다.","큐잉: “발이 아니라 허벅지 안쪽으로 패드를 모아주세요.”"],"en":["Keep the lower back comfortable.","Bring the thighs inward.","Pause briefly at the end.","Return slowly.","Keep the pelvis still.","Cue: “Bring the pads together with your inner thighs rather than your feet.”"]}'::jsonb, '{"ko":["골반을 패드에서 안정시킨다.","다리를 갑자기 모으지 않는다.","너무 큰 범위로 벌리지 않는다."],"en":["Keep the pelvis stable.","Do not snap the legs together.","Do not force an excessive starting range."]}'::jsonb),
  ('STD_HIP_EXTENSION', '{"ko":["몸통을 안정시킨다.","엉덩이에서 다리를 뒤로 보낸다.","무릎을 편안하게 유지한다.","끝에서 둔근을 조인다.","천천히 돌아온다.","큐잉: “허리로 높이를 만들지 말고 엉덩이에서 다리를 뒤로 보내주세요.”"],"en":["Stabilize the torso.","Drive the leg backward from the hip.","Keep the knee comfortably positioned.","Squeeze the glute at the end.","Return slowly.","Cue: “Move the leg backward from the hip rather than creating height with your lower back.”"]}'::jsonb, '{"ko":["허리를 꺾어 다리를 들어 올리지 않는다.","골반이 돌아가지 않게 한다.","반동을 사용하지 않는다."],"en":["Do not arch the lower back to lift the leg.","Keep the pelvis stable.","Do not use momentum."]}'::jsonb),
  ('STD_HIP_THRUST', '{"ko":["발을 안정적으로 둔다.","골반을 위쪽으로 들어 올린다.","허리가 아니라 엉덩이로 마무리한다.","위에서 잠깐 멈춘다.","천천히 내려온다.","큐잉: “허리를 꺾어 올리지 말고 골반을 앞으로 밀어 엉덩이를 조여주세요.”"],"en":["Keep the feet stable.","Drive the hips upward.","Finish with the glutes rather than the lower back.","Pause briefly at the top.","Lower slowly.","Cue: “Drive the hips forward and squeeze the glutes rather than arching your lower back.”"]}'::jsonb, '{"ko":["패드가 골반에 안정적으로 위치하도록 한다.","허리를 과하게 꺾어 올라가지 않는다.","무게를 갑자기 내려놓지 않는다."],"en":["Position the pad securely across the hips.","Do not hyperextend the lower back.","Do not drop the load suddenly."]}'::jsonb),
  ('STD_HORIZONTAL_LEG_PRESS', '{"ko":["발을 발판에 안정시킨다.","무릎과 발끝 방향을 맞춘다.","내려오는 속도를 통제한다.","발 전체로 민다.","엉덩이가 들리지 않는 범위를 사용한다.","큐잉: “무릎을 발끝 방향으로 보내면서 발판을 밀어주세요.”"],"en":["Keep the feet stable.","Align knees with toes.","Control the descent.","Press through the whole foot.","Use a range that keeps the hips stable.","Cue: “Drive your knees in the direction of your toes as you press.”"]}'::jsonb, '{"ko":["골반과 허리를 패드에 안정적으로 둔다.","무릎이 안쪽으로 무너지지 않게 한다.","무릎을 강하게 잠그지 않는다."],"en":["Keep the pelvis and lower back stable.","Do not let the knees collapse inward.","Do not forcefully lock the knees."]}'::jsonb),
  ('STD_INCLINE_CHEST_PRESS', '{"ko":["등과 골반을 안정적으로 둔다.","가슴을 세우고 시작한다.","팔꿈치를 위쪽 앞방향으로 보낸다.","내려오는 구간을 통제한다.","무게보다 일정한 움직임을 우선한다.","큐잉: “팔꿈치를 위쪽으로 밀어 올린다는 느낌으로 눌러주세요.”"],"en":["Keep your back and pelvis stable.","Start with the chest upright.","Drive the elbows upward and forward.","Control the lowering phase.","Prioritize consistent movement over heavier weight.","Cue: “Drive your elbows upward as you press.”"]}'::jsonb, '{"ko":["손잡이가 가슴 위쪽에 자연스럽게 맞도록 조절한다.","허리를 과하게 꺾어 밀지 않는다.","어깨가 불편한 깊이까지 억지로 내리지 않는다."],"en":["Align the handles naturally with the upper chest.","Do not excessively arch the lower back.","Do not force the handles into an uncomfortable depth."]}'::jsonb),
  ('STD_ISO_LATERAL_BICEPS_CURL', '{"ko":["몸통을 고정한다.","한쪽 손잡이를 어깨 쪽으로 당긴다.","위에서 잠깐 멈춘다.","천천히 내려온다.","좌우 움직임을 비교한다.","큐잉: “몸을 기울이지 말고 팔꿈치 아래만 접어주세요.”"],"en":["Keep the torso still.","Curl one handle toward the shoulder.","Pause briefly at the top.","Lower slowly.","Compare both sides.","Cue: “Keep your torso still and curl only below the elbow.”"]}'::jsonb, '{"ko":["한쪽을 할 때 몸을 기울이지 않는다.","팔꿈치를 안정시킨다.","무게를 갑자기 놓지 않는다."],"en":["Do not lean while training one side.","Keep the elbow stable.","Do not release the weight suddenly."]}'::jsonb),
  ('STD_ISO_LATERAL_CHEST_PRESS', '{"ko":["몸통을 안정적으로 유지한다.","한쪽 팔꿈치를 앞쪽으로 보낸다.","어깨를 으쓱하지 않는다.","좌우 움직임을 통제한다.","좌우 차이를 확인하며 수행한다.","큐잉: “몸은 그대로 두고 팔꿈치 하나씩 앞쪽으로 길게 보내주세요.”"],"en":["Keep the torso stable.","Drive one elbow forward.","Do not shrug.","Control both sides.","Pay attention to differences between sides.","Cue: “Keep your body still and drive one elbow forward at a time.”"]}'::jsonb, '{"ko":["양쪽 시작 위치가 어깨에 편안한지 확인한다.","한쪽을 밀며 몸통을 돌리지 않는다.","한쪽에 무게가 과하게 몰리지 않게 한다."],"en":["Make sure both starting positions feel comfortable.","Do not rotate your torso while pressing one side.","Do not allow excessive load shift to one side."]}'::jsonb),
  ('STD_ISO_LATERAL_HIGH_ROW', '{"ko":["가슴을 안정시킨다.","한쪽 팔꿈치를 아래·뒤로 보낸다.","몸통은 정면을 유지한다.","끝에서 등을 조인다.","천천히 돌아온다.","큐잉: “몸통은 정면, 팔꿈치만 허리 뒤쪽으로 보내세요.”"],"en":["Stabilize the chest.","Drive one elbow down and back.","Keep the torso facing forward.","Squeeze the back at the end.","Return slowly.","Cue: “Keep your torso forward and drive only your elbow toward your back.”"]}'::jsonb, '{"ko":["몸통을 한쪽으로 돌리지 않는다.","어깨가 앞으로 끌려가지 않게 한다.","좌우 원판을 균형 있게 장착한다."],"en":["Do not rotate the torso.","Do not let the shoulder get pulled forward.","Load both sides evenly."]}'::jsonb),
  ('STD_ISO_LATERAL_LAT_PULLDOWN', '{"ko":["가슴을 세운다.","한쪽 팔꿈치를 아래로 당긴다.","어깨를 귀에서 멀리 둔다.","몸통은 움직이지 않는다.","천천히 돌아온다.","큐잉: “몸을 옆으로 기울이지 말고 팔꿈치를 엉덩이 쪽으로 내려주세요.”"],"en":["Keep the chest up.","Drive one elbow down.","Keep the shoulder away from the ear.","Keep the torso still.","Return slowly.","Cue: “Keep your torso still and drive your elbow toward your hip.”"]}'::jsonb, '{"ko":["좌우 손잡이를 몸에 맞춘다.","한쪽을 당기며 몸을 기울이지 않는다.","손잡이를 갑자기 놓지 않는다."],"en":["Position both handles comfortably.","Do not lean to one side.","Do not release the handles abruptly."]}'::jsonb),
  ('STD_ISO_LATERAL_LOW_ROW', '{"ko":["팔꿈치를 낮게 둔다.","팔꿈치를 뒤로 보낸다.","가슴을 안정시킨다.","끝에서 등을 조인다.","무게를 천천히 돌려보낸다.","큐잉: “팔꿈치를 바지 뒷주머니 방향으로 보내주세요.”"],"en":["Keep the elbows low.","Drive the elbows backward.","Keep the chest stable.","Squeeze the back.","Return the weight slowly.","Cue: “Drive your elbows toward your back pockets.”"]}'::jsonb, '{"ko":["허리를 둥글게 말지 않는다.","몸을 뒤로 젖히지 않는다.","어깨를 으쓱하지 않는다."],"en":["Do not round the lower back.","Do not lean backward.","Do not shrug."]}'::jsonb),
  ('STD_ISO_LATERAL_ROW', '{"ko":["몸통을 정면으로 유지한다.","한쪽 팔꿈치를 뒤로 보낸다.","어깨를 낮게 유지한다.","끝에서 등을 조인다.","천천히 돌아온다.","큐잉: “몸통은 그대로, 팔꿈치만 뒤로 길게 보내주세요.”"],"en":["Keep the torso facing forward.","Drive one elbow backward.","Keep the shoulder down.","Squeeze the back.","Return slowly.","Cue: “Keep your torso still and drive only your elbow backward.”"]}'::jsonb, '{"ko":["몸통을 한쪽으로 돌리지 않는다.","어깨를 과하게 앞으로 보내지 않는다.","좌우 중량을 균형 있게 맞춘다."],"en":["Do not rotate the torso.","Do not excessively protract the shoulder.","Balance the load on both sides."]}'::jsonb),
  ('STD_ISO_LATERAL_SHOULDER_PRESS', '{"ko":["몸통을 안정시킨다.","한쪽 팔꿈치를 위로 민다.","어깨를 귀에서 멀리 둔다.","같은 경로로 돌아온다.","좌우 움직임을 비교한다.","큐잉: “몸을 기울이지 말고 팔꿈치를 천장 쪽으로 올려주세요.”"],"en":["Stabilize the torso.","Drive one elbow upward.","Keep the shoulder away from the ear.","Return along the same path.","Compare both sides.","Cue: “Keep your torso still and drive your elbow toward the ceiling.”"]}'::jsonb, '{"ko":["좌우 시작 위치를 확인한다.","한쪽을 밀며 몸을 기울이지 않는다.","어깨 통증을 참고 수행하지 않는다."],"en":["Check both starting positions.","Do not lean while pressing one side.","Do not push through shoulder pain."]}'::jsonb),
  ('STD_LATERAL_RAISE', '{"ko":["몸통을 세운다.","팔꿈치를 옆으로 들어 올린다.","어깨를 귀에서 멀리 둔다.","올라가는 속도를 통제한다.","내려오는 구간도 버틴다.","큐잉: “손이 아니라 팔꿈치로 양옆을 밀어낸다고 생각하세요.”"],"en":["Keep the torso upright.","Lift the elbows outward.","Keep the shoulders away from the ears.","Control the lift.","Control the lowering phase.","Cue: “Think about pushing outward with your elbows, not lifting with your hands.”"]}'::jsonb, '{"ko":["어깨가 편안한 높이까지만 올린다.","몸을 흔들지 않는다.","지나치게 무거운 중량을 사용하지 않는다."],"en":["Raise only to a comfortable height.","Do not swing the body.","Do not use excessive weight."]}'::jsonb),
  ('STD_LAT_PULLDOWN', '{"ko":["허벅지를 패드로 안정시킨다.","가슴을 살짝 들어준다.","팔꿈치를 아래로 당긴다.","올라갈 때 팔을 통제한다.","등을 길게 늘려준다.","큐잉: “바를 당기지 말고 팔꿈치를 바닥으로 끌어내린다고 생각하세요.”"],"en":["Secure your thighs under the pads.","Lift the chest slightly.","Drive the elbows down.","Control the arm extension.","Allow the back to lengthen.","Cue: “Drive your elbows down toward the floor rather than simply pulling the bar.”"]}'::jsonb, '{"ko":["바를 목 뒤로 당기지 않는다.","몸을 크게 뒤로 젖히지 않는다.","무게를 반동으로 당기지 않는다."],"en":["Do not pull the bar behind the neck.","Do not lean far backward.","Do not use momentum."]}'::jsonb),
  ('STD_LEG_EXTENSION', '{"ko":["등을 패드에 안정적으로 둔다.","무릎 아래쪽으로 패드를 민다.","위에서 잠깐 멈춘다.","내려올 때 천천히 버틴다.","무게보다 무릎 위치를 우선한다.","큐잉: “발로 차는 게 아니라 무릎 아래를 앞으로 길게 펴주세요.”"],"en":["Keep the back against the pad.","Extend the legs against the pad.","Pause briefly at the top.","Control the return.","Prioritize knee position over weight.","Cue: “Think about extending the lower leg forward rather than kicking.”"]}'::jsonb, '{"ko":["무릎 관절과 기구 회전축을 맞춘다.","발목 패드가 너무 높거나 낮지 않게 한다.","무릎을 강하게 튕겨 잠그지 않는다."],"en":["Align the knee joint with the machine pivot.","Position the ankle pad appropriately.","Do not snap the knees into lockout."]}'::jsonb),
  ('STD_LEG_PRESS', '{"ko":["발판에 발을 안정적으로 둔다.","무릎과 발 방향을 비슷하게 맞춘다.","내려올 때 골반 위치를 유지한다.","발판을 밀 때 발 전체로 힘을 전달한다.","올라올 때 무릎을 완전히 튕겨 잠그지 않는다.","큐잉: “발판을 발 전체로 밀면서 무릎을 발끝 방향으로 따라가게 해주세요.”"],"en":["Place your feet firmly on the platform.","Keep knees and feet generally aligned.","Maintain pelvic position as you lower.","Press through the whole foot.","Avoid snapping the knees into lockout.","Cue: “Press through the whole foot and let your knees track with your toes.”"]}'::jsonb, '{"ko":["허리와 골반이 패드에서 과하게 떨어지지 않게 한다.","무릎이 발끝 방향과 크게 어긋나지 않게 한다.","무릎을 강하게 잠그지 않는다."],"en":["Keep the lower back and pelvis stable against the pad.","Keep the knees generally tracking with the feet.","Do not forcefully lock the knees."]}'::jsonb),
  ('STD_LEG_PRESS_CALF', '{"ko":["무릎은 편안하게 유지한다.","발뒤꿈치를 아래로 내린다.","발 앞쪽으로 발판을 밀어 올린다.","위에서 종아리를 조인다.","반동 없이 반복한다.","큐잉: “무릎으로 미는 게 아니라 발목을 길게 써서 발판을 밀어주세요.”"],"en":["Keep the knees comfortably positioned.","Lower the heels.","Push the platform away through the balls of the feet.","Squeeze the calves at the top.","Repeat without bouncing.","Cue: “Use your ankles and calves to move the platform rather than driving with your knees.”"]}'::jsonb, '{"ko":["발 앞부분만 발판에 안정적으로 둔다.","발판에서 발이 빠지지 않게 한다.","무릎을 강하게 잠그지 않는다."],"en":["Keep the balls of the feet securely on the platform.","Do not let the feet slip off.","Do not forcefully lock the knees."]}'::jsonb),
  ('STD_LOW_ROW', '{"ko":["팔꿈치를 낮게 유지한다.","팔꿈치를 뒤로 당긴다.","어깨를 아래로 유지한다.","끝에서 등을 조인다.","천천히 돌아온다.","큐잉: “팔꿈치를 낮게 유지하면서 뒤로 보내주세요.”"],"en":["Keep the elbows relatively low.","Drive them backward.","Keep the shoulders down.","Squeeze the back.","Return slowly.","Cue: “Keep your elbows low and drive them backward.”"]}'::jsonb, '{"ko":["허리를 둥글게 말지 않는다.","팔꿈치를 지나치게 높이지 않는다.","몸을 뒤로 젖히지 않는다."],"en":["Do not round the lower back.","Do not raise the elbows excessively.","Do not lean back."]}'::jsonb),
  ('STD_LYING_LEG_CURL', '{"ko":["몸통을 패드에 안정시킨다.","발뒤꿈치를 엉덩이 쪽으로 당긴다.","끝에서 햄스트링을 조인다.","무게를 천천히 돌려보낸다.","반동을 사용하지 않는다.","큐잉: “골반은 패드에 두고 발뒤꿈치만 엉덩이 쪽으로 당겨주세요.”"],"en":["Keep the torso stable on the pad.","Pull the heels toward the hips.","Squeeze the hamstrings at the end.","Return the weight slowly.","Avoid momentum.","Cue: “Keep your hips down and pull your heels toward your hips.”"]}'::jsonb, '{"ko":["무릎이 기구 회전축과 맞도록 한다.","골반이 패드에서 들리지 않게 한다.","허리를 과하게 꺾지 않는다."],"en":["Align the knee with the machine pivot.","Keep the hips stable.","Do not excessively arch the lower back."]}'::jsonb),
  ('STD_MACHINE_LATERAL_RAISE', '{"ko":["어깨와 팔꿈치를 패드에 안정시킨다.","팔꿈치를 옆으로 보낸다.","몸통은 움직이지 않는다.","위에서 잠깐 멈춘다.","천천히 내린다.","큐잉: “팔로 드는 게 아니라 팔꿈치로 패드를 밀어주세요.”"],"en":["Stabilize the shoulders and elbows against the pads.","Drive the elbows outward.","Keep the torso still.","Pause briefly at the top.","Lower slowly.","Cue: “Push the pads outward with your elbows rather than lifting with your arms.”"]}'::jsonb, '{"ko":["팔 패드를 몸에 맞춘다.","몸을 옆으로 기울이지 않는다.","통증이 생기는 높이까지 올리지 않는다."],"en":["Position the arm pads correctly.","Do not lean sideways.","Do not raise into a painful range."]}'::jsonb),
  ('STD_MID_ROW', '{"ko":["가슴을 편다.","팔꿈치를 몸 옆으로 보낸다.","끝에서 잠시 멈춘다.","무게를 놓지 않고 돌아온다.","등을 길게 늘린다.","큐잉: “어깨를 뒤로 젖히는 게 아니라 팔꿈치를 뒤로 보내세요.”"],"en":["Keep the chest open.","Drive the elbows alongside the body.","Pause briefly at the end.","Return under control.","Allow the back to lengthen.","Cue: “Drive your elbows backward instead of leaning your shoulders back.”"]}'::jsonb, '{"ko":["몸통을 과하게 뒤로 젖히지 않는다.","어깨를 으쓱하지 않는다.","팔꿈치를 지나치게 뒤로 보내지 않는다."],"en":["Do not excessively lean back.","Do not shrug.","Do not drive the elbows excessively far back."]}'::jsonb),
  ('STD_MULTI_JUNGLE_GYM', '{"ko":["운동에 맞는 높이를 선택한다.","발을 안정적으로 둔다.","몸통을 움직임에 맞게 통제한다.","케이블을 갑자기 놓지 않는다.","좌우 움직임을 균형 있게 한다.","큐잉: “케이블을 당기는 것보다 움직이고 싶은 팔꿈치 방향을 먼저 잡으세요.”"],"en":["Choose the appropriate height.","Keep a stable stance.","Control the torso.","Do not release the cable suddenly.","Keep both sides balanced.","Cue: “Set the direction of your elbow before thinking about pulling the cable.”"]}'::jsonb, '{"ko":["사용할 케이블과 손잡이를 먼저 확인한다.","케이블 이동 경로를 확인한다.","무게가 너무 무거워 몸이 끌려가지 않게 한다."],"en":["Check the cable and attachment before use.","Check the cable path.","Avoid resistance that pulls you out of position."]}'::jsonb),
  ('STD_PEC_DECK', '{"ko":["가슴을 세운다.","어깨를 안정적으로 둔다.","팔꿈치를 앞쪽으로 모은다는 느낌으로 움직인다.","끝에서 가슴을 수축한다.","시작 위치로 천천히 돌아간다.","큐잉: “손이 아니라 양쪽 팔꿈치를 앞에서 만나게 해주세요.”"],"en":["Keep the chest upright.","Keep the shoulders stable.","Think about bringing the elbows forward.","Squeeze the chest at the end.","Return slowly.","Cue: “Bring your elbows together in front rather than focusing on your hands.”"]}'::jsonb, '{"ko":["팔 또는 팔꿈치 위치를 어깨에 맞춘다.","팔을 뒤로 과하게 벌리지 않는다.","반동으로 팔을 모으지 않는다."],"en":["Adjust the arm position to suit your shoulders.","Do not force the arms excessively far back.","Do not use momentum to bring the arms together."]}'::jsonb),
  ('STD_PLATE_LOADED_CHEST_PRESS', '{"ko":["시트부터 몸에 맞춘다.","발을 안정적으로 둔다.","팔꿈치를 앞쪽으로 보낸다.","원판의 움직임을 통제한다.","좌우 속도를 비슷하게 유지한다.","큐잉: “원판이 아니라 팔꿈치를 앞쪽으로 보내서 기구를 움직이세요.”"],"en":["Set the seat to fit your body first.","Keep your feet stable.","Drive your elbows forward.","Control the plate movement.","Keep both sides moving at a similar speed.","Cue: “Drive your elbows forward to move the machine, not the plates.”"]}'::jsonb, '{"ko":["좌우 원판을 균형 있게 장착한다.","원판을 반드시 고정한다.","중량 때문에 자세가 무너지면 낮춘다."],"en":["Load both sides evenly.","Secure the plates properly.","Reduce the weight if your position breaks down."]}'::jsonb),
  ('STD_PLATE_LOADED_SHOULDER_PRESS', '{"ko":["시트를 몸에 맞춘다.","팔꿈치를 위로 보낸다.","몸통을 안정시킨다.","내려오는 원판을 통제한다.","좌우 속도를 맞춘다.","큐잉: “팔을 펴는 것보다 팔꿈치를 위로 들어 올린다고 생각하세요.”"],"en":["Set the seat to fit your body.","Drive the elbows upward.","Keep the torso stable.","Control the plates on the way down.","Keep both sides moving evenly.","Cue: “Think about lifting your elbows upward rather than simply straightening your arms.”"]}'::jsonb, '{"ko":["좌우 원판을 균형 있게 장착한다.","원판을 고정한다.","무게 때문에 허리가 과하게 꺾이지 않게 한다."],"en":["Load both sides evenly.","Secure the plates.","Do not let the weight force excessive back arch."]}'::jsonb),
  ('STD_POWER_RACK', '{"ko":["바의 시작 높이를 운동에 맞춘다.","스쿼트에서는 안전바 높이를 먼저 확인한다.","발을 안정적으로 둔다.","무게보다 움직임을 우선한다.","세트 후 바를 확실하게 걸어둔다.","큐잉: “중량보다 먼저 안전바 위치를 확인하고, 내 움직임 범위 안에서 바를 통제하세요.”"],"en":["Set the bar height for the exercise.","Check safety-bar height for squats.","Keep a stable stance.","Prioritize movement quality over weight.","Re-rack the bar securely after the set.","Cue: “Check the safety-bar position before loading up, then control the bar through your usable range.”"]}'::jsonb, '{"ko":["안전바와 J컵 높이를 운동 전에 확인한다.","원판을 좌우 균형 있게 장착한다.","혼자 한계 중량에 도전하지 않는다."],"en":["Check the safety bars and J-cup height before exercising.","Load both sides evenly.","Do not attempt maximal loads alone."]}'::jsonb),
  ('STD_PREACHER_CURL', '{"ko":["겨드랑이 쪽을 패드에 안정시킨다.","손잡이를 천천히 올린다.","위에서 이두근을 조인다.","내려오는 구간을 길게 통제한다.","팔꿈치를 들지 않는다.","큐잉: “팔꿈치를 패드에 두고 아래팔만 접어주세요.”"],"en":["Stabilize the upper arms against the pad.","Curl the handle slowly.","Squeeze the biceps at the top.","Control the lowering phase.","Keep the elbows down.","Cue: “Keep your elbows on the pad and curl only the lower arms.”"]}'::jsonb, '{"ko":["팔꿈치가 패드에서 안정적으로 움직이도록 한다.","아래에서 팔을 강하게 튕겨 올리지 않는다.","손목을 과하게 꺾지 않는다."],"en":["Keep the elbows supported by the pad.","Do not jerk from the bottom.","Do not excessively bend the wrists."]}'::jsonb),
  ('STD_PULLOVER', '{"ko":["몸통을 안정시킨다.","팔꿈치를 약간 굽힌다.","팔보다 겨드랑이 아래에서 당긴다고 생각한다.","돌아갈 때 등을 길게 늘린다.","전체 구간을 통제한다.","큐잉: “팔로 누르지 말고 겨드랑이 아래쪽으로 기구를 끌어온다고 생각하세요.”"],"en":["Keep the torso stable.","Keep a slight bend in the elbows.","Think about pulling from underneath the armpits.","Allow the back to lengthen on the return.","Control the full movement.","Cue: “Think about pulling the machine down from underneath your armpits.”"]}'::jsonb, '{"ko":["어깨가 불편한 범위까지 팔을 보내지 않는다.","팔꿈치를 강하게 잠그지 않는다.","몸을 들썩여 기구를 움직이지 않는다."],"en":["Do not force the arms into an uncomfortable range.","Do not forcefully lock the elbows.","Do not swing your body."]}'::jsonb),
  ('STD_REAR_DELT', '{"ko":["가슴을 패드에 안정시킨다.","팔꿈치를 뒤쪽으로 벌린다.","손보다 팔꿈치에 집중한다.","끝에서 잠시 멈춘다.","천천히 돌아온다.","큐잉: “손을 벌리지 말고 팔꿈치를 뒤쪽으로 벌려주세요.”"],"en":["Keep the chest stable on the pad.","Drive the elbows backward and outward.","Focus on the elbows.","Pause briefly at the end.","Return slowly.","Cue: “Spread your elbows back rather than focusing on your hands.”"]}'::jsonb, '{"ko":["팔을 지나치게 뒤로 보내지 않는다.","몸을 흔들지 않는다.","어깨를 으쓱하지 않는다."],"en":["Do not force the arms excessively backward.","Do not swing the body.","Do not shrug."]}'::jsonb),
  ('STD_REAR_DELT_REVERSE_PEC', '{"ko":["가슴을 패드에 둔다.","팔꿈치를 뒤로 벌린다.","어깨를 낮게 유지한다.","끝에서 잠깐 멈춘다.","천천히 돌아온다.","큐잉: “팔을 뒤로 보내기보다 팔꿈치를 양옆 뒤쪽으로 벌려주세요.”"],"en":["Keep the chest on the pad.","Drive the elbows backward and outward.","Keep the shoulders down.","Pause briefly.","Return slowly.","Cue: “Spread your elbows out and back rather than simply moving your arms backward.”"]}'::jsonb, '{"ko":["시작 위치에서 어깨가 과하게 늘어나지 않게 한다.","팔을 지나치게 높이 올리지 않는다.","반동을 사용하지 않는다."],"en":["Avoid excessive shoulder stretch.","Do not force the arms excessively high.","Do not use momentum."]}'::jsonb),
  ('STD_ROTARY_TORSO', '{"ko":["몸통을 세운다.","복부에 힘을 유지한다.","몸통을 천천히 회전한다.","끝에서 잠깐 멈춘다.","반대쪽도 같은 범위로 수행한다.","큐잉: “팔로 기구를 돌리지 말고 몸통이 회전한다고 생각하세요.”"],"en":["Keep the torso upright.","Keep the abdomen engaged.","Rotate the torso slowly.","Pause briefly at the end.","Use a similar range on both sides.","Cue: “Do not twist with your arms; rotate through your torso.”"]}'::jsonb, '{"ko":["골반을 안정적으로 고정한다.","너무 큰 범위로 몸통을 돌리지 않는다.","반동으로 회전하지 않는다."],"en":["Keep the pelvis stable.","Do not force an excessive rotation range.","Do not use momentum."]}'::jsonb),
  ('STD_ROTATOR_MACHINE', '{"ko":["몸통을 움직이지 않는다.","팔꿈치 위치를 유지한다.","손을 천천히 움직인다.","무게보다 정확한 움직임을 우선한다.","날카로운 통증이 생기면 중단한다.","큐잉: “팔꿈치는 고정하고 손만 천천히 움직여주세요.”"],"en":["Keep the torso still.","Keep the elbow position stable.","Move the hand slowly.","Prioritize precise movement over resistance.","Stop if sharp pain occurs.","Cue: “Keep your elbow fixed and move only your hand slowly.”"]}'::jsonb, '{"ko":["팔꿈치가 기구 회전축과 적절히 맞도록 조절한다.","처음에는 가벼운 저항으로 시작한다.","작은 범위에서 정확하게 움직인다."],"en":["Align the elbow appropriately with the machine''s rotation.","Start with light resistance.","Use a controlled, comfortable range."]}'::jsonb),
  ('STD_ROW_MACHINE', '{"ko":["가슴을 세운다.","팔꿈치를 뒤로 보낸다.","손잡이보다 팔꿈치 움직임을 생각한다.","끝에서 잠깐 멈춘다.","통제하며 돌아온다.","큐잉: “가슴은 그대로 두고 팔꿈치만 뒤로 보내세요.”"],"en":["Keep the chest upright.","Drive the elbows back.","Focus on elbow movement.","Pause briefly at the end.","Return under control.","Cue: “Keep your chest still and drive your elbows backward.”"]}'::jsonb, '{"ko":["몸통을 크게 흔들지 않는다.","허리를 뒤로 젖히지 않는다.","어깨가 앞으로 과하게 끌리지 않게 한다."],"en":["Do not rock the torso.","Do not lean back.","Do not allow excessive shoulder pull."]}'::jsonb),
  ('STD_SEATED_CALF', '{"ko":["발 앞부분을 발판에 둔다.","발뒤꿈치를 아래로 천천히 내린다.","발 앞쪽으로 강하게 밀어 올라온다.","위에서 잠깐 멈춘다.","전체 움직임을 통제한다.","큐잉: “발목으로 튕기지 말고 종아리로 천천히 위아래를 만들어주세요.”"],"en":["Place the balls of the feet on the platform.","Lower the heels slowly.","Drive up through the balls of the feet.","Pause at the top.","Control the full range.","Cue: “Use the calves to control the movement rather than bouncing through the ankles.”"]}'::jsonb, '{"ko":["무릎 패드가 허벅지에 안정적으로 닿게 한다.","발이 발판에서 미끄러지지 않게 한다.","반동으로 발뒤꿈치를 튕기지 않는다."],"en":["Position the knee pad securely on the thighs.","Keep the feet from slipping.","Do not bounce the heels."]}'::jsonb),
  ('STD_SEATED_LEG_CURL', '{"ko":["몸통을 안정적으로 둔다.","발뒤꿈치를 엉덩이 방향으로 당긴다.","무릎을 움직이지 않고 다리만 접는다.","끝에서 잠깐 멈춘다.","천천히 펴준다.","큐잉: “발끝보다 발뒤꿈치를 엉덩이 쪽으로 끌어온다고 생각하세요.”"],"en":["Stabilize the torso.","Pull the heels toward the hips.","Bend the leg without moving the knee position.","Pause briefly at the end.","Return slowly.","Cue: “Think about pulling your heels toward your hips.”"]}'::jsonb, '{"ko":["무릎과 기구 회전축을 맞춘다.","패드가 다리 위치에 맞게 조절됐는지 확인한다.","엉덩이가 패드에서 뜨지 않게 한다."],"en":["Align the knee with the machine pivot.","Adjust the pads to fit the leg.","Keep the hips stable."]}'::jsonb),
  ('STD_SEATED_ROW', '{"ko":["가슴을 세운다.","팔꿈치를 뒤로 보낸다.","어깨를 으쓱하지 않는다.","끝에서 등을 조인다.","팔을 천천히 펴준다.","큐잉: “손잡이를 배로 당기기보다 팔꿈치를 뒤로 보내주세요.”"],"en":["Keep the chest upright.","Drive the elbows backward.","Do not shrug.","Squeeze the back at the end.","Slowly extend the arms.","Cue: “Drive your elbows backward rather than simply pulling the handle to your stomach.”"]}'::jsonb, '{"ko":["허리를 둥글게 말지 않는다.","몸을 뒤로 젖혀 반동을 만들지 않는다.","손잡이를 몸에 억지로 붙이지 않는다."],"en":["Do not round the lower back.","Do not lean back for momentum.","Do not force the handle against the body."]}'::jsonb),
  ('STD_SHOULDER_LATERAL_COMBO', '{"ko":["프레스에서는 팔꿈치를 위로 보낸다.","레터럴에서는 팔꿈치를 옆으로 보낸다.","몸통 반동을 줄인다.","각 동작에 맞는 중량을 사용한다.","움직임을 일정하게 유지한다.","큐잉: “프레스는 팔꿈치를 위로, 레터럴은 팔꿈치를 옆으로 보내세요.”"],"en":["Drive elbows upward during the press.","Drive elbows outward during the lateral raise.","Minimize torso momentum.","Use appropriate resistance for each movement.","Keep the movement controlled.","Cue: “Drive your elbows up for the press and out for the lateral raise.”"]}'::jsonb, '{"ko":["선택한 동작에 맞게 시트와 손잡이를 조절한다.","두 동작의 위치를 혼동하지 않는다.","어깨가 불편하면 범위를 줄인다."],"en":["Set the seat and handles for the selected movement.","Do not confuse the setups for the two movements.","Reduce the range if the shoulder feels uncomfortable."]}'::jsonb),
  ('STD_SHOULDER_PRESS', '{"ko":["머리와 등을 안정적으로 둔다.","팔꿈치를 위쪽으로 보낸다.","어깨를 으쓱하지 않는다.","내려올 때 통제한다.","무게보다 자세를 우선한다.","큐잉: “허리로 밀지 말고 팔꿈치를 위로 보내면서 밀어주세요.”"],"en":["Keep the head and back stable.","Drive the elbows upward.","Do not shrug.","Control the descent.","Prioritize position over weight.","Cue: “Drive your elbows upward without using your lower back.”"]}'::jsonb, '{"ko":["손잡이가 어깨와 자연스럽게 맞도록 시트를 조절한다.","허리를 과하게 꺾지 않는다.","어깨가 불편한 범위까지 내리지 않는다."],"en":["Adjust the seat so the handles align naturally with the shoulders.","Do not excessively arch the lower back.","Do not force an uncomfortable range."]}'::jsonb),
  ('STD_SIDE_BEND', '{"ko":["발을 안정적으로 둔다.","몸통을 옆으로 천천히 기울인다.","반대쪽으로 돌아올 때 복부 옆쪽을 사용한다.","골반 움직임을 최소화한다.","반동 없이 반복한다.","큐잉: “골반을 움직이지 말고 갈비뼈를 옆으로 내려주세요.”"],"en":["Keep the feet stable.","Bend the torso slowly to the side.","Use the side of the abdomen to return.","Minimize pelvic movement.","Repeat without momentum.","Cue: “Keep the pelvis still and bring the ribcage down to the side.”"]}'::jsonb, '{"ko":["무거운 중량으로 몸을 빠르게 굽히지 않는다.","골반을 과하게 밀어내지 않는다.","통증이 있는 범위까지 옆으로 굽히지 않는다."],"en":["Do not rapidly bend with heavy resistance.","Do not excessively shift the pelvis.","Do not force a painful side bend."]}'::jsonb),
  ('STD_SINGLE_LEG_CURL', '{"ko":["한쪽 다리 움직임에 집중한다.","발뒤꿈치를 엉덩이 쪽으로 당긴다.","허벅지를 안정시킨다.","끝에서 햄스트링을 느낀다.","천천히 내려온다.","큐잉: “허벅지는 그대로 두고 발뒤꿈치만 접어주세요.”"],"en":["Focus on one leg.","Pull the heel toward the hip.","Keep the thigh stable.","Feel the hamstrings at the end.","Lower slowly.","Cue: “Keep the thigh still and curl only the heel.”"]}'::jsonb, '{"ko":["무릎 위치를 맞춘다.","골반이 돌아가지 않게 한다.","무게 때문에 몸통이 흔들리지 않게 한다."],"en":["Align the knee properly.","Keep the pelvis from rotating.","Do not let the torso move due to excessive weight."]}'::jsonb),
  ('STD_SMITH_MACHINE', '{"ko":["운동 전에 바의 이동 경로를 확인한다.","발과 몸 위치를 운동에 맞춘다.","무게를 통제하며 움직인다.","무릎과 발끝 방향을 맞춘다.","세트가 끝나면 바를 확실하게 잠근다.","큐잉: “바를 움직이는 것보다 몸의 중심을 안정시키고 정해진 경로로 밀어주세요.”"],"en":["Check the bar path before starting.","Set your stance for the exercise.","Move under control.","Keep knees aligned with toes when appropriate.","Securely re-rack the bar after the set.","Cue: “Stabilize your body and press through the intended path rather than simply moving the bar.”"]}'::jsonb, '{"ko":["바의 잠금 위치와 안전장치를 확인한다.","양쪽 원판을 균형 있게 장착한다.","혼자 무리한 중량을 사용하지 않는다."],"en":["Check the bar locks and safety settings.","Load both sides evenly.","Do not use excessive weight alone."]}'::jsonb),
  ('STD_SQUAT_PRESS', '{"ko":["가슴을 세운다.","엉덩이를 아래로 내린다.","무릎과 발끝 방향을 맞춘다.","발 전체로 밀어 올라온다.","일정한 속도로 움직인다.","큐잉: “무릎을 안으로 모으지 말고 발끝 방향으로 그대로 밀어주세요.”"],"en":["Keep the chest upright.","Lower the hips.","Align knees with toes.","Drive up through the whole foot.","Move at a steady pace.","Cue: “Keep your knees tracking with your toes rather than letting them collapse inward.”"]}'::jsonb, '{"ko":["발 위치를 안정적으로 잡는다.","허리가 과하게 말리지 않게 한다.","안전장치 위치를 확인한다."],"en":["Set the feet securely.","Do not excessively round the lower back.","Check the safety mechanism."]}'::jsonb),
  ('STD_STANDING_CALF', '{"ko":["무릎을 편안하게 유지한다.","발뒤꿈치를 아래로 통제한다.","발 앞쪽으로 바닥을 밀며 올라온다.","위에서 종아리를 조인다.","반동 없이 반복한다.","큐잉: “발끝으로 서는 것보다 발 앞쪽으로 바닥을 밀어 올린다고 생각하세요.”"],"en":["Keep the knees comfortably positioned.","Lower the heels under control.","Drive through the balls of the feet.","Squeeze the calves at the top.","Repeat without bouncing.","Cue: “Think about pushing the floor away through the balls of your feet.”"]}'::jsonb, '{"ko":["발을 발판에 안정적으로 둔다.","발목이 불안정하게 꺾이지 않게 한다.","너무 깊게 내려가 통증을 만들지 않는다."],"en":["Keep the feet stable on the platform.","Keep the ankles stable.","Do not force excessive stretch."]}'::jsonb),
  ('STD_STANDING_LEG_CURL', '{"ko":["한쪽 다리만 움직인다.","발뒤꿈치를 엉덩이 방향으로 당긴다.","허리를 움직이지 않는다.","끝에서 잠시 멈춘다.","천천히 내린다.","큐잉: “골반은 정면에 두고 발뒤꿈치만 위로 접어주세요.”"],"en":["Move one leg at a time.","Pull the heel toward the hip.","Keep the lower back still.","Pause briefly.","Lower slowly.","Cue: “Keep your pelvis facing forward and curl only the heel upward.”"]}'::jsonb, '{"ko":["몸을 지지대에 안정적으로 둔다.","무릎 위치를 기구 회전축에 맞춘다.","골반을 비틀지 않는다."],"en":["Stabilize yourself against the support.","Align the knee with the machine pivot.","Do not rotate the pelvis."]}'::jsonb),
  ('STD_SUPER_INCLINE_PRESS', '{"ko":["등과 골반을 안정시킨다.","가슴을 세운다.","팔꿈치를 위쪽으로 보낸다.","내려오는 속도를 조절한다.","중량보다 자세를 우선한다.","큐잉: “어깨를 으쓱하지 말고 팔꿈치를 위로 밀어주세요.”"],"en":["Keep your back and pelvis stable.","Keep the chest upright.","Drive the elbows upward.","Control the descent.","Prioritize position over weight.","Cue: “Keep your shoulders down and drive your elbows upward.”"]}'::jsonb, '{"ko":["손잡이가 어깨와 팔꿈치에 자연스럽게 맞도록 한다.","허리를 과하게 꺾지 않는다.","어깨가 불편한 깊이까지 내리지 않는다."],"en":["Position the handles naturally for your shoulders and elbows.","Do not excessively arch your back.","Do not force an uncomfortable depth."]}'::jsonb),
  ('STD_TRICEPS_EXTENSION', '{"ko":["팔꿈치를 안정적으로 둔다.","팔을 아래쪽으로 펴준다.","위에서 삼두근을 조인다.","돌아올 때 천천히 굽힌다.","어깨가 따라가지 않게 한다.","큐잉: “팔꿈치를 움직이지 말고 팔꿈치 아래만 펴주세요.”"],"en":["Keep the elbows stable.","Extend the arms downward.","Squeeze the triceps at the end.","Slowly bend on the return.","Keep the shoulders from moving.","Cue: “Keep your elbows still and extend only below the elbows.”"]}'::jsonb, '{"ko":["팔꿈치를 지나치게 벌리지 않는다.","몸을 앞으로 숙여 반동을 만들지 않는다.","팔꿈치에 통증이 생기면 무게를 낮춘다."],"en":["Do not excessively flare the elbows.","Do not lean forward for momentum.","Reduce the weight if the elbows hurt."]}'::jsonb),
  ('STD_TRICEPS_PRESS', '{"ko":["몸통을 안정시킨다.","팔꿈치를 몸 옆에 둔다.","손잡이를 아래로 밀어낸다.","끝에서 삼두근을 조인다.","천천히 돌아온다.","큐잉: “어깨가 아니라 팔꿈치 아래를 펴서 손잡이를 내려주세요.”"],"en":["Stabilize the torso.","Keep the elbows close to the body.","Press the handles downward.","Squeeze the triceps at the end.","Return slowly.","Cue: “Extend below the elbows and press the handles down without using the shoulders.”"]}'::jsonb, '{"ko":["손잡이를 안정적으로 잡는다.","어깨를 으쓱하지 않는다.","팔꿈치를 지나치게 벌리지 않는다."],"en":["Grip the handles securely.","Do not shrug.","Do not excessively flare the elbows."]}'::jsonb),
  ('STD_T_BAR_ROW', '{"ko":["허리를 안정시킨다.","팔꿈치를 뒤로 당긴다.","가슴보다 등으로 당긴다고 생각한다.","끝에서 등을 조인다.","천천히 내려간다.","큐잉: “몸을 세우지 말고 팔꿈치를 뒤로 당겨 손잡이를 가져오세요.”"],"en":["Keep the lower back stable.","Drive the elbows backward.","Think about pulling with your back.","Squeeze the back.","Return slowly.","Cue: “Drive your elbows backward rather than standing your torso up.”"]}'::jsonb, '{"ko":["허리를 둥글게 말지 않는다.","몸을 세우는 반동으로 당기지 않는다.","손잡이를 갑자기 놓지 않는다."],"en":["Do not round the lower back.","Do not use torso momentum.","Do not release the handle abruptly."]}'::jsonb),
  ('STD_UPRIGHT_ROW', '{"ko":["몸통을 세운다.","팔꿈치를 옆쪽 위로 올린다.","손보다 팔꿈치에 집중한다.","위에서 잠시 멈춘다.","천천히 내린다.","큐잉: “손을 끌어올리지 말고 팔꿈치를 양옆 위로 들어주세요.”"],"en":["Keep the torso upright.","Lift the elbows up and out.","Focus on the elbows.","Pause briefly at the top.","Lower slowly.","Cue: “Lift your elbows up and out rather than pulling with your hands.”"]}'::jsonb, '{"ko":["지나치게 좁은 그립을 사용하지 않는다.","어깨가 불편한 높이까지 억지로 올리지 않는다.","무게를 튕겨 올리지 않는다."],"en":["Do not use an excessively narrow grip.","Do not force an uncomfortable height.","Do not jerk the weight upward."]}'::jsonb),
  ('STD_WIDE_LAT_PULLDOWN', '{"ko":["가슴을 세운다.","팔꿈치를 옆구리 아래로 당긴다.","어깨를 으쓱하지 않는다.","올라갈 때 천천히 보낸다.","손보다 팔꿈치에 집중한다.","큐잉: “팔꿈치를 겨드랑이 아래로 넣는 느낌으로 당겨주세요.”"],"en":["Keep the chest up.","Drive elbows down toward the sides.","Do not shrug.","Return slowly.","Focus on the elbows.","Cue: “Drive your elbows down toward your armpits.”"]}'::jsonb, '{"ko":["손을 지나치게 넓게 잡지 않는다.","몸을 크게 흔들지 않는다.","바를 억지로 가슴에 찍듯 당기지 않는다."],"en":["Do not use an excessively wide grip.","Do not swing your body.","Do not force the bar into the chest."]}'::jsonb)
) AS v(code, tips, warnings)
WHERE t.code = v.code;

UPDATE machines m
SET
  tips = t.tips,
  warnings = t.warnings,
  updated_at = NOW()
FROM standard_machine_types t
WHERE m.standard_type_id = t.id
  AND t.tips IS NOT NULL
  AND t.warnings IS NOT NULL;

UPDATE machine_settings ms
SET
  tips = t.tips,
  warnings = t.warnings,
  updated_at = NOW()
FROM machines m
JOIN standard_machine_types t ON t.id = m.standard_type_id
WHERE ms.machine_id = m.id
  AND t.tips IS NOT NULL
  AND t.warnings IS NOT NULL;

UPDATE machine_recommendations r
SET
  tips = t.tips,
  warnings = t.warnings,
  updated_at = NOW()
FROM machines m
JOIN standard_machine_types t ON t.id = m.standard_type_id
WHERE r.machine_id = m.id
  AND t.tips IS NOT NULL
  AND t.warnings IS NOT NULL;
