import { Router } from 'express';
import { healthRouter } from './health.routes.js';
import { authRouter } from './auth.routes.js';
import { meRouter } from './me.routes.js';
import { machineRouter } from './machine.routes.js';
import { brandRouter } from './brand.routes.js';
import { recommendationRouter } from './recommendation.routes.js';
import { metaRouter } from './meta.routes.js';
import { userRouter } from './user.routes.js';
import { favoriteRouter } from './favorite.routes.js';
import { historyRouter } from './history.routes.js';
import { gymRouter } from './gym.routes.js';
import { communityRouter } from './community.routes.js';
import { machineRequestRouter } from './machine-request.routes.js';
import { ownerRouter } from './owner.routes.js';
import { trainerRouter } from './trainer.routes.js';
import { notificationRouter } from './notification.routes.js';
import { adminRouter } from './admin.routes.js';
import { qrRouter } from './qr.routes.js';
import { workoutLogRouter } from './workout-log.routes.js';
import { motivationMediaRouter } from './motivation-media.routes.js';
import { liveDashboardRouter } from './live-dashboard.routes.js';
import { locationRouter } from './location.routes.js';
import { muscleGroupImageRouter } from './muscle-group-image.routes.js';
import { photoBoardRouter } from './photo-board.routes.js';
import { machineTradeRouter } from './machine-trade.routes.js';
import { onlinePtRouter } from './online-pt.routes.js';
import { pushNotificationRouter } from './push-notification.routes.js';
import { friendRouter } from './friend.routes.js';
import { complianceRouter } from './compliance.routes.js';
import { inspectionRouter } from './inspection.routes.js';

export const apiRouter = Router();

apiRouter.use(healthRouter);
apiRouter.use(complianceRouter);
apiRouter.use('/auth', authRouter);
/** Spec alias: /me/providers (same handlers as /auth/me/providers). */
apiRouter.use('/me', meRouter);
/** Prefixed — never mount at API root with router-level auth (blocks /auth/login). */
apiRouter.use('/inspection', inspectionRouter);
apiRouter.use('/users', userRouter);
apiRouter.use('/machines', machineRouter);
apiRouter.use('/brands', brandRouter);
apiRouter.use('/recommendations', recommendationRouter);
apiRouter.use('/favorites', favoriteRouter);
apiRouter.use('/history', historyRouter);
apiRouter.use('/gyms', gymRouter);
apiRouter.use('/meta', metaRouter);
apiRouter.use('/community', communityRouter);
apiRouter.use('/machine-requests', machineRequestRouter);
apiRouter.use('/owner', ownerRouter);
apiRouter.use('/trainer', trainerRouter);
apiRouter.use('/notifications', notificationRouter);
apiRouter.use('/admin', adminRouter);
apiRouter.use('/qr', qrRouter);
apiRouter.use('/workout-logs', workoutLogRouter);
apiRouter.use('/motivation-media', motivationMediaRouter);
apiRouter.use('/live', liveDashboardRouter);
apiRouter.use('/locations', locationRouter);
apiRouter.use('/muscle-group-images', muscleGroupImageRouter);
apiRouter.use('/photo-board', photoBoardRouter);
apiRouter.use('/machine-trades', machineTradeRouter);
apiRouter.use('/online-pt', onlinePtRouter);
apiRouter.use('/push', pushNotificationRouter);
apiRouter.use('/friends', friendRouter);
